--------------------------------------------------------
-- Archivo creado  - domingo-julio-30-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLEADOS
--------------------------------------------------------

  CREATE TABLE "GARCIA"."EMPLEADOS" 
   (	"ID_EMPLEADO" NUMBER(20,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"PRIMER_APELLIDO" VARCHAR2(20 BYTE), 
	"SEGUNDO_APELLIDO" VARCHAR2(20 BYTE), 
	"TELEFONO" NUMBER(11,0), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"PUESTO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FACTURACION
--------------------------------------------------------

  CREATE TABLE "GARCIA"."FACTURACION" 
   (	"ID_FACTURAS" NUMBER(20,0), 
	"ID_MATERIALES" NUMBER(20,0), 
	"FECHA_FACTURA" DATE, 
	"MONTO" NUMBER(20,2)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HERRAMIENTAS
--------------------------------------------------------

  CREATE TABLE "GARCIA"."HERRAMIENTAS" 
   (	"ID_HERRAMIENTA" NUMBER(20,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"TIPO_HERRAMIENTA" VARCHAR2(20 BYTE), 
	"USO_HERRAMIENTA" VARCHAR2(20 BYTE), 
	"ID_PROVEEDORES" NUMBER(20,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HISTORIAL_PRESTAMOS
--------------------------------------------------------

  CREATE TABLE "GARCIA"."HISTORIAL_PRESTAMOS" 
   (	"ID_HISTORIAL" NUMBER(20,0), 
	"ID_EMPLEADO" NUMBER(20,0), 
	"ID_HERRAMIENTA" NUMBER(20,0), 
	"ID_RESERVAS" NUMBER(20,0), 
	"ID_MANTENIMIENTO" NUMBER(20,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MANTENIMIENTO
--------------------------------------------------------

  CREATE TABLE "GARCIA"."MANTENIMIENTO" 
   (	"ID_MANTENIMIENTO" NUMBER(20,0), 
	"ID_HERRAMIENTA" NUMBER(20,0), 
	"FECHA_INGRESO" DATE, 
	"FECHA_EGRESO" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MATERIALES
--------------------------------------------------------

  CREATE TABLE "GARCIA"."MATERIALES" 
   (	"ID_MATERIALES" NUMBER(20,0), 
	"ID_PROVEEDORES" NUMBER(20,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"FECHA_INGRESO" DATE, 
	"FECHA_EGRESO" DATE, 
	"TAMAÑO" NUMBER(20,0), 
	"CANTIDAD" NUMBER(20,0), 
	"USO" VARCHAR2(20 BYTE), 
	"PRECIO" NUMBER(20,2)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NOTIFICACIONES
--------------------------------------------------------

  CREATE TABLE "GARCIA"."NOTIFICACIONES" 
   (	"ID_NOTIFICACIONES" NUMBER(20,0), 
	"ID_HISTORIAL" NUMBER(20,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROVEEDORES
--------------------------------------------------------

  CREATE TABLE "GARCIA"."PROVEEDORES" 
   (	"ID_PROVEEDORES" NUMBER(20,0), 
	"NOMBRE_EMPRESA" VARCHAR2(20 BYTE), 
	"PRODUCTO_SOLICITADO" VARCHAR2(20 BYTE), 
	"CEDULA_EMPRESA" NUMBER(20,0), 
	"FECHA_PEDIDO" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RESERVAS
--------------------------------------------------------

  CREATE TABLE "GARCIA"."RESERVAS" 
   (	"ID_RESERVAS" NUMBER(20,0), 
	"ID_EMPLEADO" NUMBER(20,0), 
	"ID_HERRAMIENTA" NUMBER(20,0), 
	"FECHA_INGRESO" DATE, 
	"FECHA_EGRESO" DATE, 
	"ESTADO_HERRAMIENTA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "GARCIA"."USUARIOS" 
   (	"ID_USUARIO" NUMBER(20,0), 
	"ID_MATERIALES" NUMBER(20,0), 
	"CONTRASEÑA" NUMBER(20,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"TELEFONO" NUMBER(20,0), 
	"EMAIL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for View MOSTRAR_EMPLEADO
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "GARCIA"."MOSTRAR_EMPLEADO" ("ID_EMPLEADO", "NOMBRE", "PRIMER_APELLIDO", "SEGUNDO_APELLIDO", "TELEFONO", "EMAIL", "PUESTO") AS 
  SELECT "ID_EMPLEADO","NOMBRE","PRIMER_APELLIDO","SEGUNDO_APELLIDO","TELEFONO","EMAIL","PUESTO"
FROM EMPLEADOS
;
--------------------------------------------------------
--  DDL for View MOSTRAR_HERRAMIENTAS
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "GARCIA"."MOSTRAR_HERRAMIENTAS" ("ID_HERRAMIENTA", "NOMBRE", "TIPO_HERRAMIENTA", "USO_HERRAMIENTA", "PROVEEDOR") AS 
  SELECT A.ID_HERRAMIENTA, A.NOMBRE, A.TIPO_HERRAMIENTA, A.USO_HERRAMIENTA,B.NOMBRE_EMPRESA AS PROVEEDOR
FROM HERRAMIENTAS A
INNER JOIN PROVEEDORES B ON A.ID_PROVEEDORES = B.ID_PROVEEDORES
;
--------------------------------------------------------
--  DDL for View MOSTRAR_MANTENIMIENTO
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "GARCIA"."MOSTRAR_MANTENIMIENTO" ("ID_MANTENIMIENTO", "HERRAMIENTA", "FECHA_INGRESO", "FECHA_EGRESO") AS 
  SELECT A.ID_MANTENIMIENTO, B.NOMBRE AS HERRAMIENTA, A.FECHA_INGRESO, A.FECHA_EGRESO
FROM MANTENIMIENTO A
INNER JOIN HERRAMIENTAS B ON A.ID_HERRAMIENTA = B.ID_HERRAMIENTA
;
--------------------------------------------------------
--  DDL for View MOSTRAR_PROVEEDORES
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "GARCIA"."MOSTRAR_PROVEEDORES" ("ID_PROVEEDORES", "NOMBRE_EMPRESA", "PRODUCTO_SOLICITADO", "CEDULA_EMPRESA", "FECHA_PEDIDO") AS 
  SELECT "ID_PROVEEDORES","NOMBRE_EMPRESA","PRODUCTO_SOLICITADO","CEDULA_EMPRESA","FECHA_PEDIDO"
FROM PROVEEDORES
;
--------------------------------------------------------
--  DDL for View MOSTRAR_USUARIOS
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "GARCIA"."MOSTRAR_USUARIOS" ("NOMBRE", "TELEFONO", "EMAIL", "MATERIAL") AS 
  SELECT A.NOMBRE, A.TELEFONO, A.EMAIL, B.NOMBRE AS MATERIAL
FROM USUARIOS A
INNER JOIN MATERIALES B ON A.ID_MATERIALES = B.ID_MATERIALES
;
REM INSERTING into GARCIA.EMPLEADOS
SET DEFINE OFF;
REM INSERTING into GARCIA.FACTURACION
SET DEFINE OFF;
REM INSERTING into GARCIA.HERRAMIENTAS
SET DEFINE OFF;
REM INSERTING into GARCIA.HISTORIAL_PRESTAMOS
SET DEFINE OFF;
REM INSERTING into GARCIA.MANTENIMIENTO
SET DEFINE OFF;
REM INSERTING into GARCIA.MATERIALES
SET DEFINE OFF;
REM INSERTING into GARCIA.NOTIFICACIONES
SET DEFINE OFF;
REM INSERTING into GARCIA.PROVEEDORES
SET DEFINE OFF;
REM INSERTING into GARCIA.RESERVAS
SET DEFINE OFF;
REM INSERTING into GARCIA.USUARIOS
SET DEFINE OFF;
REM INSERTING into GARCIA.MOSTRAR_EMPLEADO
SET DEFINE OFF;
REM INSERTING into GARCIA.MOSTRAR_HERRAMIENTAS
SET DEFINE OFF;
REM INSERTING into GARCIA.MOSTRAR_MANTENIMIENTO
SET DEFINE OFF;
REM INSERTING into GARCIA.MOSTRAR_PROVEEDORES
SET DEFINE OFF;
REM INSERTING into GARCIA.MOSTRAR_USUARIOS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C007760
--------------------------------------------------------

  CREATE UNIQUE INDEX "GARCIA"."SYS_C007760" ON "GARCIA"."PROVEEDORES" ("ID_PROVEEDORES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007761
--------------------------------------------------------

  CREATE UNIQUE INDEX "GARCIA"."SYS_C007761" ON "GARCIA"."MATERIALES" ("ID_MATERIALES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007763
--------------------------------------------------------

  CREATE UNIQUE INDEX "GARCIA"."SYS_C007763" ON "GARCIA"."USUARIOS" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007765
--------------------------------------------------------

  CREATE UNIQUE INDEX "GARCIA"."SYS_C007765" ON "GARCIA"."FACTURACION" ("ID_FACTURAS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007767
--------------------------------------------------------

  CREATE UNIQUE INDEX "GARCIA"."SYS_C007767" ON "GARCIA"."MANTENIMIENTO" ("ID_MANTENIMIENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007768
--------------------------------------------------------

  CREATE UNIQUE INDEX "GARCIA"."SYS_C007768" ON "GARCIA"."EMPLEADOS" ("ID_EMPLEADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007769
--------------------------------------------------------

  CREATE UNIQUE INDEX "GARCIA"."SYS_C007769" ON "GARCIA"."HERRAMIENTAS" ("ID_HERRAMIENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007771
--------------------------------------------------------

  CREATE UNIQUE INDEX "GARCIA"."SYS_C007771" ON "GARCIA"."RESERVAS" ("ID_RESERVAS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007775
--------------------------------------------------------

  CREATE UNIQUE INDEX "GARCIA"."SYS_C007775" ON "GARCIA"."NOTIFICACIONES" ("ID_NOTIFICACIONES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007778
--------------------------------------------------------

  CREATE UNIQUE INDEX "GARCIA"."SYS_C007778" ON "GARCIA"."HISTORIAL_PRESTAMOS" ("ID_HISTORIAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007768
--------------------------------------------------------

  CREATE UNIQUE INDEX "GARCIA"."SYS_C007768" ON "GARCIA"."EMPLEADOS" ("ID_EMPLEADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007765
--------------------------------------------------------

  CREATE UNIQUE INDEX "GARCIA"."SYS_C007765" ON "GARCIA"."FACTURACION" ("ID_FACTURAS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007769
--------------------------------------------------------

  CREATE UNIQUE INDEX "GARCIA"."SYS_C007769" ON "GARCIA"."HERRAMIENTAS" ("ID_HERRAMIENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007778
--------------------------------------------------------

  CREATE UNIQUE INDEX "GARCIA"."SYS_C007778" ON "GARCIA"."HISTORIAL_PRESTAMOS" ("ID_HISTORIAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007767
--------------------------------------------------------

  CREATE UNIQUE INDEX "GARCIA"."SYS_C007767" ON "GARCIA"."MANTENIMIENTO" ("ID_MANTENIMIENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007761
--------------------------------------------------------

  CREATE UNIQUE INDEX "GARCIA"."SYS_C007761" ON "GARCIA"."MATERIALES" ("ID_MATERIALES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007775
--------------------------------------------------------

  CREATE UNIQUE INDEX "GARCIA"."SYS_C007775" ON "GARCIA"."NOTIFICACIONES" ("ID_NOTIFICACIONES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007760
--------------------------------------------------------

  CREATE UNIQUE INDEX "GARCIA"."SYS_C007760" ON "GARCIA"."PROVEEDORES" ("ID_PROVEEDORES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007771
--------------------------------------------------------

  CREATE UNIQUE INDEX "GARCIA"."SYS_C007771" ON "GARCIA"."RESERVAS" ("ID_RESERVAS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007763
--------------------------------------------------------

  CREATE UNIQUE INDEX "GARCIA"."SYS_C007763" ON "GARCIA"."USUARIOS" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Procedure ELIMINAR_EMPLEADOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "GARCIA"."ELIMINAR_EMPLEADOS" 
(P_ID_EMPLEADO        EMPLEADOS.ID_EMPLEADO%TYPE,
P_NOMBRE              EMPLEADOS.NOMBRE%TYPE,
P_PRIMER_APELLIDO     EMPLEADOS.PRIMER_APELLIDO%TYPE,
P_SEGUNDO_APELLIDO    EMPLEADOS.SEGUNDO_APELLIDO%TYPE,
P_TELEFONO            EMPLEADOS.TELEFONO%TYPE,
P_MAIL                EMPLEADOS.MAIL%TYPE,
P_PUESTO              EMPLEADOS.PUESTO%TYPE
)
AS
BEGIN
DELETE FROM EMPLEADOS
WHERE ID_EMPLEADO = P_ID_EMPLEADO;
END ELIMINAR_EMPLEADOS;

/
--------------------------------------------------------
--  DDL for Procedure ELIMINAR_HERRAMIENTA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "GARCIA"."ELIMINAR_HERRAMIENTA" 
(P_ID_HERRAMIENTA     HERRAMIENTAS.ID_HERRAMIENTA%TYPE,
P_ID_PROVEEDORES      HERRAMIENTAS.ID_PROVEEEDORES%TYPE,
P_NOMBRE              HERRAMIENTAS.NOMBRE%TYPE,
P_TIPO_HERRAMIENTA    HERRAMIENTAS.TIPO_HERRAMIENTA%TYPE,
P_USO_HERRAMIENTA     HERRAMIENTAS.USO_HERRAMIENTA%TYPE
)
AS
BEGIN
DELETE FROM HERRAMIENTAS
WHERE ID_HERRAMIENTA = P_ID_HERRAMIENTA;
END ELIMINAR_HERRAMIENTA;

/
--------------------------------------------------------
--  DDL for Procedure ELIMINAR_HISTORIAL_PRESTAMOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "GARCIA"."ELIMINAR_HISTORIAL_PRESTAMOS" 
(P_ID_HISTORIAL       HISTORIAL_PRESTAMOS.ID_HISTORIAL%TYPE,
P_ID_HERRAMIENTA      HISTORIAL_PRESTAMOS.ID_HERRAMIENTA%TYPE,
P_ID_EMPLEADO         HISTORIAL_PRESTAMOS.ID_EMPLEADO%TYPE,
P_ID_RESERVAS         HISTORIAL_PRESTAMOS.ID_RESERVAS%TYPE,
P_ID_MANTENIMIENTO    HISTORIAL_PRESTAMOS.ID_MANTENIMIENTO%TYPE
)
AS
BEGIN
DELETE FROM HISTORIAL_PRESTAMOS
WHERE ID_HISTORIAL = P_ID_HISTORIAL;
END ELIMINAR_HISTORIAL_PRESTAMOS;

/
--------------------------------------------------------
--  DDL for Procedure ELIMINAR_MANTENIMIENTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "GARCIA"."ELIMINAR_MANTENIMIENTO" 
(P_ID_MANTENIMIENTO   MANTENIMIENTO.ID_MANTENIMIENTO%TYPE,
P_ID_HERRAMIENTA      MANTENIMIENTO.ID_HERRAMIENTA%TYPE,
P_FECHA_INGRESO       MANTENIMIENTO.FECHA_INGRESO%TYPE,
P_FECHA_EGRESO        MANTENIMIENTO.FECHA_EGRESO%TYPE
)
AS
BEGIN
DELETE FROM MANTENIMIENTO
WHERE ID_MANTENIMIENTO = P_ID_MANTENIMIENTO;
END ELIMINAR_MANTENIMIENTO;

/
--------------------------------------------------------
--  DDL for Procedure ELIMINAR_MATERIALES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "GARCIA"."ELIMINAR_MATERIALES" 
(P_ID_MATERIALES      MATERIALES.ID_MATERIALES%TYPE,
P_ID_PROVEEDORES      MATERIALES.ID_PROVEEDORES%TYPE,
P_NOMBRE              MATERIALES.NOMBRE%TYPE,
P_FECHA_INGRESO       MATERIALES.FECHA_INGRESO%TYPE,
P_FECHA_EGRESO        MATERIALES.FECHA_EGRESO%TYPE,
P_TAMAÑO              MATERIALES.TAMAÑO%TYPE,
P_CANTIDAD            MATERIALES.CANTIDAD%TYPE,
P_USO                 MATERIALES.USO%TYPE,
P_PRECIO              MATERIALES.PRECIO%TYPE
)
AS
BEGIN
DELETE FROM MATERIALES
WHERE ID_MATERIALES = P_ID_MATERIALES;
END ELIMINAR_MATERIALES;

/
--------------------------------------------------------
--  DDL for Procedure ELIMINAR_PROVEEDORES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "GARCIA"."ELIMINAR_PROVEEDORES" 
(P_ID_PROVEEDORES       PROVEEDORES.ID_PROVEEDORES%TYPE,
P_NOMBRE_EMPRESA        PROVEEDORES.NOMBRE_EMPRESA%TYPE,
P_PRODUCTO_SOLICITADO   PROVEEDORES.PRODUCTO_SOLICITADO%TYPE,
P_CEDULA_EMPRESA        PROVEEDORES.CEDULA_EMPRESA%TYPE,
P_FECHA_PEDIDO          PROVEEDORES.FECHA_PEDIDO%TYPE
)
AS
BEGIN
DELETE FROM PROVEEDORES
WHERE ID_PROVEEDORES = P_ID_PROVEEDORES;
END ELIMINAR_PROVEEDORES;

/
--------------------------------------------------------
--  DDL for Procedure ELIMINAR_RESERVA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "GARCIA"."ELIMINAR_RESERVA" 
(P_ID_RESERVAS         RESERVAS.ID_RESERVAS%TYPE,
P_ID_EMPLEADO          RESERVAS.ID_EMPLEADO%TYPE,
P_ID_HERRAMIENTA       RESERVAS.ID_HERRAMIENTA%TYPE,
P_FECHA_INGRESO        RESERVAS.FECHA_INGRESO%TYPE,
P_FECHA_EGRESO         RESERVAS.FECHA_EGRESO%TYPE,
P_ESTADO_HERRAMIENTA   RESERVAS.ESTADO_HERRAMIENTA%TYPE
)
AS
BEGIN
DELETE FROM RESERVAS
WHERE ID_RESERVAS = P_ID_RESERVAS;
END ELIMINAR_RESERVA;

/
--------------------------------------------------------
--  DDL for Procedure ELIMINAR_USUARIOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "GARCIA"."ELIMINAR_USUARIOS" 
(P_ID_USUARIO          USUARIOS.ID_USUARIO%TYPE,
P_ID_MATERIALES        USUARIOS.ID_MATERIALES%TYPE,
P_CONTRASEÑA           USUARIOS.CONTRASEÑA%TYPE,
P_NOMBRE               USUARIOS.NOMBRE%TYPE,
P_TELEFONO             USUARIOS.TELEFONO%TYPE,
P_EMAIL                USUARIOS.EMAIL%TYPE
)
AS
BEGIN
DELETE FROM USUARIOS
WHERE ID_USUARIO = P_ID_USUARIO;
END ELIMINAR_USUARIOS;

/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_EMPLEADOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "GARCIA"."INSERTAR_EMPLEADOS" (
    P_ID_EMPLEADO        EMPLEADOS.ID_EMPLEADO%TYPE,
    P_NOMBRE              EMPLEADOS.NOMBRE%TYPE,
    P_PRIMER_APELLIDO     EMPLEADOS.PRIMER_APELLIDO%TYPE,
    P_SEGUNDO_APELLIDO    EMPLEADOS.SEGUNDO_APELLIDO%TYPE,
    P_TELEFONO            EMPLEADOS.TELEFONO%TYPE,
    P_EMAIL                EMPLEADOS.EMAIL%TYPE,
    P_PUESTO              EMPLEADOS.PUESTO%TYPE
)
AS

  BEGIN
    INSERTAR_EMPLEADOS (
        P_ID_EMPLEADO        => 1,
        P_NOMBRE              => 'Juan',
        P_PRIMER_APELLIDO     => 'Pérez',
        P_SEGUNDO_APELLIDO    => 'Gómez',
        P_TELEFONO            => '555-1234',
        P_EMAIL               => 'juan.perez@example.com',
        P_PUESTO              => 'Analista'
    );

    INSERTAR_EMPLEADOS (
        P_ID_EMPLEADO        => 2,
        P_NOMBRE              => 'María',
        P_PRIMER_APELLIDO     => 'López',
        P_SEGUNDO_APELLIDO    => 'García',
        P_TELEFONO            => '555-5678',
        P_EMAIL               => 'maria.lopez@example.com',
        P_PUESTO              => 'Gerente'
    );

    -- Agrega más inserciones con datos genéricos si lo deseas
END; INSERTAR_EMPLEADOS;     

/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_FACTURA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "GARCIA"."INSERTAR_FACTURA" (
    P_ID_FACTURAS       FACTURACION.ID_FACTURAS%TYPE,
    P_ID_MATERIALES         FACTURACION.ID_MATERIALES%TYPE,
    P_FECHA_FACTURA      FACTURACION.FECHA_FACTURA%TYPE,
    P_MONTO              FACTURACION.MONTO%TYPE
)
AS
BEGIN
    INSERT INTO FACTURACION (
        ID_FACTURAS,   
        ID_MATERIALES, 
        FECHA_FACTURA,  
        MONTO
    )
    VALUES (
        P_ID_FACTURAS,    
        P_MATERIALES,   
        P_FECHA_FACTURA, 
        P_MONTO
    );
END INSERTAR_FACTURA;       

/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_HERRAMIENTA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "GARCIA"."INSERTAR_HERRAMIENTA" (
    p_id_herramienta   IN herramientas.id_herramienta%TYPE,
    p_id_proveedores   IN herramientas.id_proveedores%TYPE,
    p_nombre           IN herramientas.nombre%TYPE,
    p_tipo_herramienta  IN herramientas.tipo_herramienta%TYPE,
    p_uso_herramienta   IN herramientas.uso_herramienta%TYPE
) AS
BEGIN
    INSERT INTO herramientas (
        id_herramienta,
        id_proveedores,
        nombre,
        tipo_herramienta,
        uso_herramienta
    ) VALUES (
        p_id_herramienta,
        p_id_proveedores,
        p_nombre,
        p_tipo_herramienta,
        p_uso_herramienta
    );
END insertar_herramienta;

/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_HISTORIAL_PRESTAMOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "GARCIA"."INSERTAR_HISTORIAL_PRESTAMOS" 
(P_ID_HISTORIAL       HISTORIAL_PRESTAMOS.ID_HISTORIAL%TYPE,
P_ID_HERRAMIENTA      HISTORIAL_PRESTAMOS.ID_HERRAMIENTA%TYPE,
P_ID_EMPLEADO         HISTORIAL_PRESTAMOS.ID_EMPLEADO%TYPE,
P_ID_RESERVAS         HISTORIAL_PRESTAMOS.ID_RESERVAS%TYPE,
P_ID_MANTENIMIENTO    HISTORIAL_PRESTAMOS.ID_MANTENIMIENTO%TYPE
)
AS
BEGIN
INSERT INTO HISTORIAL_PRESTAMOS
(ID_HISTORIAL,   
ID_HERRAMIENTA, 
ID_EMPLEADO,  
ID_RESERVAS,
ID_MANTENIMIENTO
)
VALUES
(P_ID_HISTORIAL,    
P_ID_HERRAMIENTA,   
P_ID_EMPLEADO, 
P_ID_RESERVAS,
P_ID_MANTENIMIENTO
);
END INSERTAR_HISTORIAL_PRESTAMOS;

/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_MANTENIMIENTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "GARCIA"."INSERTAR_MANTENIMIENTO" 
(P_ID_MANTENIMIENTO   MANTENIMIENTO.ID_MANTENIMIENTO%TYPE,
P_ID_HERRAMIENTA      MANTENIMIENTO.ID_HERRAMIENTA%TYPE,
P_FECHA_INGRESO       MANTENIMIENTO.FECHA_INGRESO%TYPE,
P_FECHA_EGRESO        MANTENIMIENTO.FECHA_EGRESO%TYPE
)
AS
BEGIN
INSERT INTO MANTENIMIENTO
(ID_MANTENIMIENTO,   
ID_HERRAMIENTA, 
FECHA_INGRESO,  
FECHA_EGRESO
)
VALUES
(P_ID_MANTENIMIENTO,    
P_ID_HERRAMIENTA,   
P_FECHA_INGRESO, 
P_FECHA_EGRESO
);
END INSERTAR_MANTENIMIENTO;

/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_MATERIALES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "GARCIA"."INSERTAR_MATERIALES" 
(P_ID_MATERIALES      MATERIALES.ID_EMPLEADO%TYPE,
P_ID_PROVEEDORES      MATERIALES.ID_PROVEEDORES%TYPE,
P_NOMBRE              MATERIALES.NOMBRE%TYPE,
P_FECHA_INGRESO       MATERIALES.FECHA_INGRESO%TYPE,
P_FECHA_EGRESO        MATERIALES.FECHA_EGRESO%TYPE,
P_TAMAÑO              MATERIALES.TAMAÑO%TYPE,
P_CANTIDAD            MATERIALES.CANTIDAD%TYPE,
P_USO                 MATERIALES.USO%TYPE,
P_PRECIO              MATERIALES.PRECIO%TYPE
)
AS
BEGIN
INSERT INTO MATERIALES
(ID_MATERIALES,
ID_PROVEEDORES,   
NOMBRE, 
FECHA_INGRESO,  
FECHA_EGRESO,   
TAMAÑO,
CANTIDAD,
USO,
PRECIO
)
VALUES
(P_ID_MATERIALES,
P_ID_PROVEEDORES,
P_NOMBRE,   
P_FECHA_INGRESO, 
P_FECHA_EGRESO,  
P_TAMAÑO,   
P_CANTIDAD,
P_USO,
P_PRECIO
);
END INSERTAR_MATERIALES;

/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_PROVEEDORES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "GARCIA"."INSERTAR_PROVEEDORES" 
(P_ID_PROVEEDORES       PROVEEDORES.ID_PROVEEDORES%TYPE,
P_NOMBRE_EMPRESA        PROVEEDORES.NOMBRE_EMPRESA%TYPE,
P_PRODUCTO_SOLICITADO   PROVEEDORES.PRODUCTO_SOLICITADO%TYPE,
P_CEDULA_EMPRESA        PROVEEDORES.CEDULA_EMPRESA%TYPE,
P_FECHA_PEDIDO          PROVEEDORES.FECHA_PEDIDO%TYPE
)
AS
BEGIN
INSERT INTO PROVEEDORES
(ID_PROVEEDORES,   
NOMBRE_EMPRESA, 
PRODUCTO_SOLICITADO,  
CEDULA_EMPRESA,
FECHA_PEDIDO
)
VALUES
(P_ID_PROVEEDORES,    
P_NOMBRE_EMPRESA,   
P_PRODUCTO_SOLICITADO, 
P_CEDULA_EMPRESA,
P_FECHA_PEDIDO
);
END INSERTAR_PROVEEDORES;

/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_RESERVA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "GARCIA"."INSERTAR_RESERVA" (
    p_id_reservas        IN reservas.id_reservas%TYPE,
    p_id_empleado        IN reservas.id_empleado%TYPE,
    p_id_herramienta     IN reservas.id_herramienta%TYPE,
    p_fecha_ingreso      IN reservas.fecha_ingreso%TYPE,
    p_fecha_egreso       IN reservas.fecha_egreso%TYPE,
    p_estado_herramienta IN reservas.estado_herramienta%TYPE
) AS
BEGIN
    INSERT INTO reservas (
        id_reservas,
        id_empleado,
        id_herramienta,
        fecha_ingreso,
        fecha_egreso,
        estado_herramienta
    ) VALUES (
        p_id_reservas,
        p_id_empleado,
        p_id_herramienta,
        p_fecha_ingreso,
        p_fecha_egreso,
        p_estado_herramienta
    );
END insertar_reserva; 

/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_USUARIOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "GARCIA"."INSERTAR_USUARIOS" 
(P_ID_USUARIO          USUARIOS.ID_USUARIO%TYPE,
P_ID_MATERIALES        USUARIOS.ID_MATERIALES%TYPE,
P_CONTRASEÑA           USUARIOS.CONTRASEÑA%TYPE,
P_NOMBRE               USUARIOS.NOMBRE%TYPE,
P_TELEFONO             USUARIOS.TELEFONO%TYPE,
P_EMAIL                USUARIOS.EMAIL%TYPE
)
AS
BEGIN
INSERT INTO USUARIOS
(ID_USUARIO,   
ID_MATERIALES, 
CONTRASEÑA,  
NOMBRE,
TELEFONO,
EMAIL
)
VALUES
(P_ID_USUARIO,    
P_ID_MATERIALES,   
P_CONTRASEÑA, 
P_NOMBRE,
P_TELEFONO,
P_EMAIL
);
END INSERTAR_USUARIOS;

/
--------------------------------------------------------
--  DDL for Procedure MODIFICAR_EMPLEADOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "GARCIA"."MODIFICAR_EMPLEADOS" 
(P_ID_EMPLEADO        EMPLEADOS.ID_EMPLEADO%TYPE,
P_NOMBRE              EMPLEADOS.NOMBRE%TYPE,
P_PRIMER_APELLIDO     EMPLEADOS.PRIMER_APELLIDO%TYPE,
P_SEGUNDO_APELLIDO    EMPLEADOS.SEGUNDO_APELLIDO%TYPE,
P_TELEFONO            EMPLEADOS.TELEFONO%TYPE,
P_MAIL                EMPLEADOS.MAIL%TYPE,
P_PUESTO              EMPLEADOS.PUESTO%TYPE
)
AS
BEGIN
UPDATE EMPLEADOS SET
NOMBRE = P_NOMBRE,
PRIMER_APELLIDO = P_PRIMER_APELLIDO,
SEGUNDO_APELLIDO = P_SEGUNDO_APELLIDO,
TELEFONO = P_TELEFONO,
MAIL = P_MAIL,
PUESTO = P_PUESTO
WHERE ID_EMPLEADO = P_ID_EMPLEADO;
END MODIFICAR_EMPLEADOS;

/
--------------------------------------------------------
--  DDL for Procedure MODIFICAR_FACTURA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "GARCIA"."MODIFICAR_FACTURA" 
(P_ID_FACTURAS       FACTURACION.ID_FACTURAS%TYPE,
P_MATERIALES         FACTURACION.MATERIALES%TYPE,
P_FECHA_FACTURA      FACTURACION.FECHA_FACTURA%TYPE,
P_MONTO              FACTURACION.MONTO%TYPE
)
AS
BEGIN
UPDATE FACTURACION SET
MATERIALES = P_MATERIALES,
FECHA_FACTURA = P_FECHA_FACTURA,
MONTO = P_MONTO
WHERE ID_FACTURAS = P_ID_FACTURAS;
END MODIFICAR_FACTURA;

/
--------------------------------------------------------
--  DDL for Procedure MODIFICAR_HERRAMIENTA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "GARCIA"."MODIFICAR_HERRAMIENTA" 
(P_ID_HERRAMIENTA     HERRAMIENTAS.ID_HERRAMIENTA%TYPE,
P_ID_PROVEEDORES      HERRAMIENTAS.ID_PROVEEEDORES%TYPE,
P_NOMBRE              HERRAMIENTAS.NOMBRE%TYPE,
P_TIPO_HERRAMIENTA    HERRAMIENTAS.TIPO_HERRAMIENTA%TYPE,
P_USO_HERRAMIENTA     HERRAMIENTAS.USO_HERRAMIENTA%TYPE
)
AS
BEGIN
UPDATE HERRAMIENTAS SET
ID_PROVEEEDORES = P_ID_PROVEEDORES,
NOMBRE = P_NOMBRE,
TIPO_HERRAMIENTA = P_TIPO_HERRAMIENTA,
USO_HERRAMIENTA = P_USO_HERRAMIENTA
WHERE ID_HERRAMIENTA = P_ID_HERRAMIENTA;
END MODIFICAR_HERRAMIENTA;

/
--------------------------------------------------------
--  DDL for Procedure MODIFICAR_HISTORIAL_PRESTAMOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "GARCIA"."MODIFICAR_HISTORIAL_PRESTAMOS" 
(P_ID_HISTORIAL       HISTORIAL_PRESTAMOS.ID_HISTORIAL%TYPE,
P_ID_HERRAMIENTA      HISTORIAL_PRESTAMOS.ID_HERRAMIENTA%TYPE,
P_ID_EMPLEADO         HISTORIAL_PRESTAMOS.ID_EMPLEADO%TYPE,
P_ID_RESERVAS         HISTORIAL_PRESTAMOS.ID_RESERVAS%TYPE,
P_ID_MANTENIMIENTO    HISTORIAL_PRESTAMOS.ID_MANTENIMIENTO%TYPE
)
AS
BEGIN
UPDATE HISTORIAL_PRESTAMOS SET
ID_HERRAMIENTA = P_ID_HERRAMIENTA,
ID_EMPLEADO = P_ID_EMPLEADO,
ID_RESERVAS = P_ID_RESERVAS,
ID_MANTENIMIENTO = P_ID_MANTENIMIENTO
WHERE ID_HISTORIAL = P_ID_HISTORIAL;
END MODIFICAR_HISTORIAL_PRESTAMOS;

/
--------------------------------------------------------
--  DDL for Procedure MODIFICAR_MANTENIMIENTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "GARCIA"."MODIFICAR_MANTENIMIENTO" 
(P_ID_MANTENIMIENTO   MANTENIMIENTO.ID_MANTENIMIENTO%TYPE,
P_ID_HERRAMIENTA      MANTENIMIENTO.ID_HERRAMIENTA%TYPE,
P_FECHA_INGRESO       MANTENIMIENTO.FECHA_INGRESO%TYPE,
P_FECHA_EGRESO        MANTENIMIENTO.FECHA_EGRESO%TYPE
)
AS
BEGIN
UPDATE MANTENIMIENTO SET
ID_HERRAMIENTA = P_ID_HERRAMIENTA,
FECHA_INGRESO = P_FECHA_INGRESO,
FECHA_EGRESO = P_FECHA_EGRESO
WHERE ID_MANTENIMIENTO = P_ID_MANTENIMIENTO;
END MODIFICAR_MANTENIMIENTO;

/
--------------------------------------------------------
--  DDL for Procedure MODIFICAR_MATERIALES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "GARCIA"."MODIFICAR_MATERIALES" 
(P_ID_MATERIALES      MATERIALES.ID_MATERIALES%TYPE,
P_ID_PROVEEDORES      MATERIALES.ID_PROVEEDORES%TYPE,
P_NOMBRE              MATERIALES.NOMBRE%TYPE,
P_FECHA_INGRESO       MATERIALES.FECHA_INGRESO%TYPE,
P_FECHA_EGRESO        MATERIALES.FECHA_EGRESO%TYPE,
P_TAMAÑO              MATERIALES.TAMAÑO%TYPE,
P_CANTIDAD            MATERIALES.CANTIDAD%TYPE,
P_USO                 MATERIALES.USO%TYPE,
P_PRECIO              MATERIALES.PRECIO%TYPE
)
AS
BEGIN
UPDATE  MATERIALES SET
ID_PROVEEDORES = P_ID_PROVEEDORES,
NOMBRE = P_NOMBRE,
FECHA_INGRESO = P_FECHA_INGRESO,
FECHA_EGRESO = P_FECHA_EGRESO,
TAMAÑO = P_TAMAÑO,
CANTIDAD = P_CANTIDAD,
USO = P_USO,
PRECIO = P_PRECIO
WHERE ID_MATERIALES = P_ID_MATERIALES;
END MODIFICAR_MATERIALES;

/
--------------------------------------------------------
--  DDL for Procedure MODIFICAR_PROVEEDORES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "GARCIA"."MODIFICAR_PROVEEDORES" 
(P_ID_PROVEEDORES       PROVEEDORES.ID_PROVEEDORES%TYPE,
P_NOMBRE_EMPRESA        PROVEEDORES.NOMBRE_EMPRESA%TYPE,
P_PRODUCTO_SOLICITADO   PROVEEDORES.PRODUCTO_SOLICITADO%TYPE,
P_CEDULA_EMPRESA        PROVEEDORES.CEDULA_EMPRESA%TYPE,
P_FECHA_PEDIDO          PROVEEDORES.FECHA_PEDIDO%TYPE
)
AS
BEGIN
UPDATE PROVEEDORES SET
NOMBRE_EMPRESA = P_NOMBRE_EMPRESA,
PRODUCTO_SOLICITADO = P_PRODUCTO_SOLICITADO,
CEDULA_EMPRESA = P_CEDULA_EMPRESA,
FECHA_PEDIDO = P_FECHA_PEDIDO
WHERE ID_PROVEEDORES = P_ID_PROVEEDORES;
END MODIFICAR_PROVEEDORES;

/
--------------------------------------------------------
--  DDL for Procedure MODIFICAR_RESERVA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "GARCIA"."MODIFICAR_RESERVA" 
(P_ID_RESERVAS         RESERVAS.ID_RESERVAS%TYPE,
P_ID_EMPLEADO          RESERVAS.ID_EMPLEADO%TYPE,
P_ID_HERRAMIENTA       RESERVAS.ID_HERRAMIENTA%TYPE,
P_FECHA_INGRESO        RESERVAS.FECHA_INGRESO%TYPE,
P_FECHA_EGRESO         RESERVAS.FECHA_EGRESO%TYPE,
P_ESTADO_HERRAMIENTA   RESERVAS.ESTADO_HERRAMIENTA%TYPE
)
AS
BEGIN
UPDATE  RESERVAS SET
ID_EMPLEADO = P_ID_EMPLEADO,
ID_HERRAMIENTA = P_ID_HERRAMIENTA,
FECHA_INGRESO = P_FECHA_INGRESO,
FECHA_EGRESO = P_FECHA_EGRESO,
ESTADO_HERRAMIENTA = P_ESTADO_HERRAMIENTA
WHERE ID_RESERVAS = P_ID_RESERVAS;
END MODIFICAR_RESERVA;

/
--------------------------------------------------------
--  DDL for Procedure MODIFICAR_USUARIOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "GARCIA"."MODIFICAR_USUARIOS" 
(P_ID_USUARIO          USUARIOS.ID_USUARIO%TYPE,
P_ID_MATERIALES        USUARIOS.ID_MATERIALES%TYPE,
P_CONTRASEÑA           USUARIOS.CONTRASEÑA%TYPE,
P_NOMBRE               USUARIOS.NOMBRE%TYPE,
P_TELEFONO             USUARIOS.TELEFONO%TYPE,
P_EMAIL                USUARIOS.EMAIL%TYPE
)
AS
BEGIN
UPDATE USUARIOS SET
ID_MATERIALES = P_ID_MATERIALES,
CONTRASEÑA = P_CONTRASEÑA,
NOMBRE = P_NOMBRE,
TELEFONO = P_TELEFONO,
EMAIL = P_EMAIL
WHERE ID_USUARIO = P_ID_USUARIO;
END MODIFICAR_USUARIOS;

/
--------------------------------------------------------
--  Constraints for Table EMPLEADOS
--------------------------------------------------------

  ALTER TABLE "GARCIA"."EMPLEADOS" ADD PRIMARY KEY ("ID_EMPLEADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FACTURACION
--------------------------------------------------------

  ALTER TABLE "GARCIA"."FACTURACION" ADD PRIMARY KEY ("ID_FACTURAS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HERRAMIENTAS
--------------------------------------------------------

  ALTER TABLE "GARCIA"."HERRAMIENTAS" ADD PRIMARY KEY ("ID_HERRAMIENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HISTORIAL_PRESTAMOS
--------------------------------------------------------

  ALTER TABLE "GARCIA"."HISTORIAL_PRESTAMOS" ADD PRIMARY KEY ("ID_HISTORIAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MANTENIMIENTO
--------------------------------------------------------

  ALTER TABLE "GARCIA"."MANTENIMIENTO" ADD PRIMARY KEY ("ID_MANTENIMIENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "GARCIA"."MANTENIMIENTO" MODIFY ("ID_HERRAMIENTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MATERIALES
--------------------------------------------------------

  ALTER TABLE "GARCIA"."MATERIALES" ADD PRIMARY KEY ("ID_MATERIALES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table NOTIFICACIONES
--------------------------------------------------------

  ALTER TABLE "GARCIA"."NOTIFICACIONES" ADD PRIMARY KEY ("ID_NOTIFICACIONES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROVEEDORES
--------------------------------------------------------

  ALTER TABLE "GARCIA"."PROVEEDORES" ADD PRIMARY KEY ("ID_PROVEEDORES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESERVAS
--------------------------------------------------------

  ALTER TABLE "GARCIA"."RESERVAS" ADD PRIMARY KEY ("ID_RESERVAS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "GARCIA"."USUARIOS" ADD PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FACTURACION
--------------------------------------------------------

  ALTER TABLE "GARCIA"."FACTURACION" ADD FOREIGN KEY ("ID_MATERIALES")
	  REFERENCES "GARCIA"."MATERIALES" ("ID_MATERIALES") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HERRAMIENTAS
--------------------------------------------------------

  ALTER TABLE "GARCIA"."HERRAMIENTAS" ADD FOREIGN KEY ("ID_PROVEEDORES")
	  REFERENCES "GARCIA"."PROVEEDORES" ("ID_PROVEEDORES") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HISTORIAL_PRESTAMOS
--------------------------------------------------------

  ALTER TABLE "GARCIA"."HISTORIAL_PRESTAMOS" ADD FOREIGN KEY ("ID_EMPLEADO")
	  REFERENCES "GARCIA"."EMPLEADOS" ("ID_EMPLEADO") ENABLE;
  ALTER TABLE "GARCIA"."HISTORIAL_PRESTAMOS" ADD FOREIGN KEY ("ID_HERRAMIENTA")
	  REFERENCES "GARCIA"."HERRAMIENTAS" ("ID_HERRAMIENTA") ENABLE;
  ALTER TABLE "GARCIA"."HISTORIAL_PRESTAMOS" ADD FOREIGN KEY ("ID_RESERVAS")
	  REFERENCES "GARCIA"."RESERVAS" ("ID_RESERVAS") ENABLE;
  ALTER TABLE "GARCIA"."HISTORIAL_PRESTAMOS" ADD FOREIGN KEY ("ID_MANTENIMIENTO")
	  REFERENCES "GARCIA"."MANTENIMIENTO" ("ID_MANTENIMIENTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MATERIALES
--------------------------------------------------------

  ALTER TABLE "GARCIA"."MATERIALES" ADD FOREIGN KEY ("ID_PROVEEDORES")
	  REFERENCES "GARCIA"."PROVEEDORES" ("ID_PROVEEDORES") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESERVAS
--------------------------------------------------------

  ALTER TABLE "GARCIA"."RESERVAS" ADD FOREIGN KEY ("ID_EMPLEADO")
	  REFERENCES "GARCIA"."EMPLEADOS" ("ID_EMPLEADO") ENABLE;
  ALTER TABLE "GARCIA"."RESERVAS" ADD FOREIGN KEY ("ID_HERRAMIENTA")
	  REFERENCES "GARCIA"."HERRAMIENTAS" ("ID_HERRAMIENTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "GARCIA"."USUARIOS" ADD FOREIGN KEY ("ID_MATERIALES")
	  REFERENCES "GARCIA"."MATERIALES" ("ID_MATERIALES") ENABLE;
