  CREATE TABLE "EMPLEADOS" 
   ("ID_EMPLEADO" NUMBER(20,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"PRIMER_APELLIDO" VARCHAR2(20 BYTE), 
	"SEGUNDO_APELLIDO" VARCHAR2(20 BYTE), 
	"TELEFONO" NUMBER(11,0), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"PUESTO" VARCHAR2(20 BYTE)
   );
   
CREATE TABLE "FACTURACION" 
   (	"ID_FACTURAS" NUMBER(20,0), 
	"ID_MATERIALES" NUMBER(20,0), 
	"FECHA_FACTURA" DATE, 
	"MONTO" NUMBER(20,2)
   ); 
   
CREATE TABLE "HERRAMIENTAS" 
   (	"ID_HERRAMIENTA" NUMBER(20,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"TIPO_HERRAMIENTA" VARCHAR2(20 BYTE), 
	"USO_HERRAMIENTA" VARCHAR2(20 BYTE), 
	"ID_PROVEEDORES" NUMBER(20,0)
   );
   
   CREATE TABLE "HISTORIAL_PRESTAMOS" 
   (	"ID_HISTORIAL" NUMBER(20,0), 
	"ID_EMPLEADO" NUMBER(20,0), 
	"ID_HERRAMIENTA" NUMBER(20,0), 
	"ID_RESERVAS" NUMBER(20,0), 
	"ID_MANTENIMIENTO" NUMBER(20,0)
   );
   
   CREATE TABLE "GARCIA"."MANTENIMIENTO" 
   (	"ID_MANTENIMIENTO" NUMBER(20,0), 
	"ID_HERRAMIENTA" NUMBER(20,0), 
	"FECHA_INGRESO" DATE, 
	"FECHA_EGRESO" DATE
   );
   
    CREATE TABLE "GARCIA"."MATERIALES" 
   (	"ID_MATERIALES" NUMBER(20,0), 
	"ID_PROVEEDORES" NUMBER(20,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"FECHA_INGRESO" DATE, 
	"FECHA_EGRESO" DATE, 
	"TAMAÑO" NUMBER(20,0), 
	"CANTIDAD" NUMBER(20,0), 
	"USO" VARCHAR2(20 BYTE), 
	"PRECIO" NUMBER(20,2)
   );  
   
   CREATE TABLE "GARCIA"."NOTIFICACIONES" 
   (	"ID_NOTIFICACIONES" NUMBER(20,0), 
	"ID_HISTORIAL" NUMBER(20,0)
   );
   
   CREATE TABLE "GARCIA"."PROVEEDORES" 
   (	"ID_PROVEEDORES" NUMBER(20,0), 
	"NOMBRE_EMPRESA" VARCHAR2(20 BYTE), 
	"PRODUCTO_SOLICITADO" VARCHAR2(20 BYTE), 
	"CEDULA_EMPRESA" NUMBER(20,0), 
	"FECHA_PEDIDO" DATE
   );
   
   CREATE TABLE "GARCIA"."RESERVAS" 
   (	"ID_RESERVAS" NUMBER(20,0), 
	"ID_EMPLEADO" NUMBER(20,0), 
	"ID_HERRAMIENTA" NUMBER(20,0), 
	"FECHA_INGRESO" DATE, 
	"FECHA_EGRESO" DATE, 
	"ESTADO_HERRAMIENTA" VARCHAR2(20 BYTE)
   );
   
   CREATE TABLE "GARCIA"."USUARIOS" 
   (	"ID_USUARIO" NUMBER(20,0), 
	"ID_MATERIALES" NUMBER(20,0), 
	"CONTRASEÑA" NUMBER(20,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"TELEFONO" NUMBER(20,0), 
	"EMAIL" VARCHAR2(50 BYTE)
   );
   
REM INSERTING into GARCIA.EMPLEADOS
SET DEFINE OFF;
REM INSERTING into GARCIA.FACTURACION
SET DEFINE OFF;
REM INSERTING into GARCIA.HERRAMIENTAS
SET DEFINE OFF;
REM INSERTING into GARCIA.HISTORIAL_PRESTAMOS
SET DEFINE OFF;
REM INSERTING into GARCIA.MANTENIMIENTO
SET DEFINE OFF;
REM INSERTING into GARCIA.MATERIALES
SET DEFINE OFF;
REM INSERTING into GARCIA.NOTIFICACIONES
SET DEFINE OFF;
REM INSERTING into GARCIA.PROVEEDORES
SET DEFINE OFF;
REM INSERTING into GARCIA.RESERVAS
SET DEFINE OFF;
REM INSERTING into GARCIA.USUARIOS
SET DEFINE OFF;

CREATE UNIQUE INDEX "GARCIA"."SYS_C007760" ON "GARCIA"."PROVEEDORES" ("ID_PROVEEDORES");
CREATE UNIQUE INDEX "GARCIA"."SYS_C007761" ON "GARCIA"."MATERIALES" ("ID_MATERIALES");
CREATE UNIQUE INDEX "GARCIA"."SYS_C007763" ON "GARCIA"."USUARIOS" ("ID_USUARIO");
CREATE UNIQUE INDEX "GARCIA"."SYS_C007765" ON "GARCIA"."FACTURACION" ("ID_FACTURAS");
CREATE UNIQUE INDEX "GARCIA"."SYS_C007767" ON "GARCIA"."MANTENIMIENTO" ("ID_MANTENIMIENTO");
CREATE UNIQUE INDEX "GARCIA"."SYS_C007768" ON "GARCIA"."EMPLEADOS" ("ID_EMPLEADO");
CREATE UNIQUE INDEX "GARCIA"."SYS_C007769" ON "GARCIA"."HERRAMIENTAS" ("ID_HERRAMIENTA");
CREATE UNIQUE INDEX "GARCIA"."SYS_C007771" ON "GARCIA"."RESERVAS" ("ID_RESERVAS");
CREATE UNIQUE INDEX "GARCIA"."SYS_C007775" ON "GARCIA"."NOTIFICACIONES" ("ID_NOTIFICACIONES");
CREATE UNIQUE INDEX "GARCIA"."SYS_C007765" ON "GARCIA"."FACTURACION" ("ID_FACTURAS");
CREATE UNIQUE INDEX "GARCIA"."SYS_C007778" ON "GARCIA"."HISTORIAL_PRESTAMOS" ("ID_HISTORIAL");

ALTER TABLE "GARCIA"."EMPLEADOS" ADD PRIMARY KEY ("ID_EMPLEADO");
ALTER TABLE "GARCIA"."FACTURACION" ADD PRIMARY KEY ("ID_FACTURAS");
ALTER TABLE "GARCIA"."HERRAMIENTAS" ADD PRIMARY KEY ("ID_HERRAMIENTA");
ALTER TABLE "GARCIA"."HISTORIAL_PRESTAMOS" ADD PRIMARY KEY ("ID_HISTORIAL");
ALTER TABLE "GARCIA"."MANTENIMIENTO" ADD PRIMARY KEY ("ID_MANTENIMIENTO");
ALTER TABLE "GARCIA"."MATERIALES" ADD PRIMARY KEY ("ID_MATERIALES");
ALTER TABLE "GARCIA"."NOTIFICACIONES" ADD PRIMARY KEY ("ID_NOTIFICACIONES");
ALTER TABLE "GARCIA"."PROVEEDORES" ADD PRIMARY KEY ("ID_PROVEEDORES");
ALTER TABLE "GARCIA"."RESERVAS" ADD PRIMARY KEY ("ID_RESERVAS");
ALTER TABLE "GARCIA"."USUARIOS" ADD PRIMARY KEY ("ID_USUARIO");

ALTER TABLE "GARCIA"."FACTURACION" ADD FOREIGN KEY ("ID_MATERIALES")
	  REFERENCES "GARCIA"."MATERIALES" ("ID_MATERIALES") ENABLE;

ALTER TABLE "GARCIA"."HERRAMIENTAS" ADD FOREIGN KEY ("ID_PROVEEDORES")
	  REFERENCES "GARCIA"."PROVEEDORES" ("ID_PROVEEDORES") ENABLE;

 ALTER TABLE "GARCIA"."HISTORIAL_PRESTAMOS" ADD FOREIGN KEY ("ID_EMPLEADO")
	  REFERENCES "GARCIA"."EMPLEADOS" ("ID_EMPLEADO") ENABLE;
ALTER TABLE "GARCIA"."HISTORIAL_PRESTAMOS" ADD FOREIGN KEY ("ID_HERRAMIENTA")
	  REFERENCES "GARCIA"."HERRAMIENTAS" ("ID_HERRAMIENTA") ENABLE;
ALTER TABLE "GARCIA"."HISTORIAL_PRESTAMOS" ADD FOREIGN KEY ("ID_RESERVAS")
	  REFERENCES "GARCIA"."RESERVAS" ("ID_RESERVAS") ENABLE;
ALTER TABLE "GARCIA"."HISTORIAL_PRESTAMOS" ADD FOREIGN KEY ("ID_MANTENIMIENTO")
	  REFERENCES "GARCIA"."MANTENIMIENTO" ("ID_MANTENIMIENTO") ENABLE;
    
ALTER TABLE "GARCIA"."MATERIALES" ADD FOREIGN KEY ("ID_PROVEEDORES")
	  REFERENCES "GARCIA"."PROVEEDORES" ("ID_PROVEEDORES") ENABLE;

ALTER TABLE "GARCIA"."RESERVAS" ADD FOREIGN KEY ("ID_EMPLEADO")
	  REFERENCES "GARCIA"."EMPLEADOS" ("ID_EMPLEADO") ENABLE;
ALTER TABLE "GARCIA"."RESERVAS" ADD FOREIGN KEY ("ID_HERRAMIENTA")
	  REFERENCES "GARCIA"."HERRAMIENTAS" ("ID_HERRAMIENTA") ENABLE;
    
ALTER TABLE "GARCIA"."USUARIOS" ADD FOREIGN KEY ("ID_MATERIALES")
	  REFERENCES "GARCIA"."MATERIALES" ("ID_MATERIALES") ENABLE;
    
set define off;

CREATE OR REPLACE PROCEDURE "GARCIA"."ELIMINAR_EMPLEADOS" 
(P_ID_EMPLEADO        EMPLEADOS.ID_EMPLEADO%TYPE
)
AS
BEGIN
DELETE FROM EMPLEADOS
WHERE ID_EMPLEADO = P_ID_EMPLEADO;
END ELIMINAR_EMPLEADOS;

/

  CREATE OR REPLACE PROCEDURE "GARCIA"."ELIMINAR_HERRAMIENTA" 
(P_ID_HERRAMIENTA     HERRAMIENTAS.ID_HERRAMIENTA%TYPE,
P_ID_PROVEEDORES      HERRAMIENTAS.ID_PROVEEDORES%TYPE,
P_NOMBRE              HERRAMIENTAS.NOMBRE%TYPE,
P_TIPO_HERRAMIENTA    HERRAMIENTAS.TIPO_HERRAMIENTA%TYPE,
P_USO_HERRAMIENTA     HERRAMIENTAS.USO_HERRAMIENTA%TYPE
)
AS
BEGIN
DELETE FROM HERRAMIENTAS
WHERE ID_HERRAMIENTA = P_ID_HERRAMIENTA;
END ELIMINAR_HERRAMIENTA;

/
    
CREATE OR REPLACE PROCEDURE "GARCIA"."ELIMINAR_HISTORIAL_PRESTAMOS" 
(P_ID_HISTORIAL       HISTORIAL_PRESTAMOS.ID_HISTORIAL%TYPE,
P_ID_HERRAMIENTA      HISTORIAL_PRESTAMOS.ID_HERRAMIENTA%TYPE,
P_ID_EMPLEADO         HISTORIAL_PRESTAMOS.ID_EMPLEADO%TYPE,
P_ID_RESERVAS         HISTORIAL_PRESTAMOS.ID_RESERVAS%TYPE,
P_ID_MANTENIMIENTO    HISTORIAL_PRESTAMOS.ID_MANTENIMIENTO%TYPE
)
AS
BEGIN
DELETE FROM HISTORIAL_PRESTAMOS
WHERE ID_HISTORIAL = P_ID_HISTORIAL;
END ELIMINAR_HISTORIAL_PRESTAMOS;

/   

 CREATE OR REPLACE PROCEDURE "GARCIA"."ELIMINAR_MANTENIMIENTO" 
(P_ID_MANTENIMIENTO   MANTENIMIENTO.ID_MANTENIMIENTO%TYPE,
P_ID_HERRAMIENTA      MANTENIMIENTO.ID_HERRAMIENTA%TYPE,
P_FECHA_INGRESO       MANTENIMIENTO.FECHA_INGRESO%TYPE,
P_FECHA_EGRESO        MANTENIMIENTO.FECHA_EGRESO%TYPE
)
AS
BEGIN
DELETE FROM MANTENIMIENTO
WHERE ID_MANTENIMIENTO = P_ID_MANTENIMIENTO;
END ELIMINAR_MANTENIMIENTO;

/

CREATE OR REPLACE PROCEDURE "GARCIA"."ELIMINAR_MATERIALES" 
(P_ID_MATERIALES      MATERIALES.ID_MATERIALES%TYPE,
P_ID_PROVEEDORES      MATERIALES.ID_PROVEEDORES%TYPE,
P_NOMBRE              MATERIALES.NOMBRE%TYPE,
P_FECHA_INGRESO       MATERIALES.FECHA_INGRESO%TYPE,
P_FECHA_EGRESO        MATERIALES.FECHA_EGRESO%TYPE,
P_TAMAÑO              MATERIALES.TAMAÑO%TYPE,
P_CANTIDAD            MATERIALES.CANTIDAD%TYPE,
P_USO                 MATERIALES.USO%TYPE,
P_PRECIO              MATERIALES.PRECIO%TYPE
)
AS
BEGIN
DELETE FROM MATERIALES
WHERE ID_MATERIALES = P_ID_MATERIALES;
END ELIMINAR_MATERIALES;

CREATE OR REPLACE PROCEDURE "GARCIA"."ELIMINAR_PROVEEDORES" 
(P_ID_PROVEEDORES       PROVEEDORES.ID_PROVEEDORES%TYPE,
P_NOMBRE_EMPRESA        PROVEEDORES.NOMBRE_EMPRESA%TYPE,
P_PRODUCTO_SOLICITADO   PROVEEDORES.PRODUCTO_SOLICITADO%TYPE,
P_CEDULA_EMPRESA        PROVEEDORES.CEDULA_EMPRESA%TYPE,
P_FECHA_PEDIDO          PROVEEDORES.FECHA_PEDIDO%TYPE
)
AS
BEGIN
DELETE FROM PROVEEDORES
WHERE ID_PROVEEDORES = P_ID_PROVEEDORES;
END ELIMINAR_PROVEEDORES;

/

CREATE OR REPLACE PROCEDURE "GARCIA"."ELIMINAR_RESERVA" 
(P_ID_RESERVAS         RESERVAS.ID_RESERVAS%TYPE,
P_ID_EMPLEADO          RESERVAS.ID_EMPLEADO%TYPE,
P_ID_HERRAMIENTA       RESERVAS.ID_HERRAMIENTA%TYPE,
P_FECHA_INGRESO        RESERVAS.FECHA_INGRESO%TYPE,
P_FECHA_EGRESO         RESERVAS.FECHA_EGRESO%TYPE,
P_ESTADO_HERRAMIENTA   RESERVAS.ESTADO_HERRAMIENTA%TYPE
)
AS
BEGIN
DELETE FROM RESERVAS
WHERE ID_RESERVAS = P_ID_RESERVAS;
END ELIMINAR_RESERVA;

CREATE OR REPLACE PROCEDURE "GARCIA"."ELIMINAR_USUARIOS" 
(P_ID_USUARIO          USUARIOS.ID_USUARIO%TYPE,
P_ID_MATERIALES        USUARIOS.ID_MATERIALES%TYPE,
P_CONTRASEÑA           USUARIOS.CONTRASEÑA%TYPE,
P_NOMBRE               USUARIOS.NOMBRE%TYPE,
P_TELEFONO             USUARIOS.TELEFONO%TYPE,
P_EMAIL                USUARIOS.EMAIL%TYPE
)
AS
BEGIN
DELETE FROM USUARIOS
WHERE ID_USUARIO = P_ID_USUARIO;
END ELIMINAR_USUARIOS;


CREATE OR REPLACE PROCEDURE "GARCIA"."INSERTAR_EMPLEADOS" (
    P_ID_EMPLEADO        EMPLEADOS.ID_EMPLEADO%TYPE,
    P_NOMBRE              EMPLEADOS.NOMBRE%TYPE,
    P_PRIMER_APELLIDO     EMPLEADOS.PRIMER_APELLIDO%TYPE,
    P_SEGUNDO_APELLIDO    EMPLEADOS.SEGUNDO_APELLIDO%TYPE,
    P_TELEFONO            EMPLEADOS.TELEFONO%TYPE,
    P_EMAIL                EMPLEADOS.EMAIL%TYPE,
    P_PUESTO              EMPLEADOS.PUESTO%TYPE
)
AS
BEGIN
    INSERT INTO EMPLEADOS VALUES(
        P_ID_EMPLEADO,
        P_NOMBRE,
        P_PRIMER_APELLIDO,
        P_SEGUNDO_APELLIDO,
        P_TELEFONO,
        P_EMAIL,
        P_PUESTO
    );
END INSERTAR_EMPLEADOS;

CREATE OR REPLACE PROCEDURE "GARCIA"."INSERTAR_FACTURA" (
    P_ID_FACTURAS       FACTURACION.ID_FACTURAS%TYPE,
    P_ID_MATERIALES      FACTURACION.ID_MATERIALES%TYPE,
    P_FECHA_FACTURA      FACTURACION.FECHA_FACTURA%TYPE,
    P_MONTO              FACTURACION.MONTO%TYPE
)
AS
BEGIN
    INSERT INTO FACTURACION (
        ID_FACTURAS,   
        ID_MATERIALES, 
        FECHA_FACTURA,  
        MONTO
    )
    VALUES (
        P_ID_FACTURAS,    
        P_ID_MATERIALES,   
        P_FECHA_FACTURA, 
        P_MONTO
    );
END INSERTAR_FACTURA;       

/

CREATE OR REPLACE PROCEDURE "GARCIA"."INSERTAR_HERRAMIENTA" (
    p_id_herramienta   IN herramientas.id_herramienta%TYPE,
    p_id_proveedores   IN herramientas.id_proveedores%TYPE,
    p_nombre           IN herramientas.nombre%TYPE,
    p_tipo_herramienta  IN herramientas.tipo_herramienta%TYPE,
    p_uso_herramienta   IN herramientas.uso_herramienta%TYPE
) AS
BEGIN
    INSERT INTO herramientas (
        id_herramienta,
        id_proveedores,
        nombre,
        tipo_herramienta,
        uso_herramienta
    ) VALUES (
        p_id_herramienta,
        p_id_proveedores,
        p_nombre,
        p_tipo_herramienta,
        p_uso_herramienta
    );
END insertar_herramienta;

CREATE OR REPLACE PROCEDURE "GARCIA"."INSERTAR_HISTORIAL_PRESTAMOS" 
(P_ID_HISTORIAL       HISTORIAL_PRESTAMOS.ID_HISTORIAL%TYPE,
P_ID_HERRAMIENTA      HISTORIAL_PRESTAMOS.ID_HERRAMIENTA%TYPE,
P_ID_EMPLEADO         HISTORIAL_PRESTAMOS.ID_EMPLEADO%TYPE,
P_ID_RESERVAS         HISTORIAL_PRESTAMOS.ID_RESERVAS%TYPE,
P_ID_MANTENIMIENTO    HISTORIAL_PRESTAMOS.ID_MANTENIMIENTO%TYPE
)
AS
BEGIN
INSERT INTO HISTORIAL_PRESTAMOS
(ID_HISTORIAL,   
ID_HERRAMIENTA, 
ID_EMPLEADO,  
ID_RESERVAS,
ID_MANTENIMIENTO
)
VALUES
(P_ID_HISTORIAL,    
P_ID_HERRAMIENTA,   
P_ID_EMPLEADO, 
P_ID_RESERVAS,
P_ID_MANTENIMIENTO
);
END INSERTAR_HISTORIAL_PRESTAMOS;

/

 CREATE OR REPLACE PROCEDURE "GARCIA"."INSERTAR_MANTENIMIENTO" 
(P_ID_MANTENIMIENTO   MANTENIMIENTO.ID_MANTENIMIENTO%TYPE,
P_ID_HERRAMIENTA      MANTENIMIENTO.ID_HERRAMIENTA%TYPE,
P_FECHA_INGRESO       MANTENIMIENTO.FECHA_INGRESO%TYPE,
P_FECHA_EGRESO        MANTENIMIENTO.FECHA_EGRESO%TYPE
)
AS
BEGIN
INSERT INTO MANTENIMIENTO
(ID_MANTENIMIENTO,   
ID_HERRAMIENTA, 
FECHA_INGRESO,  
FECHA_EGRESO
)
VALUES
(P_ID_MANTENIMIENTO,    
P_ID_HERRAMIENTA,   
P_FECHA_INGRESO, 
P_FECHA_EGRESO
);
END INSERTAR_MANTENIMIENTO;

/

 CREATE OR REPLACE PROCEDURE "GARCIA"."INSERTAR_MATERIALES" 
(P_ID_MATERIALES      MATERIALES.ID_MATERIALES%TYPE,
P_ID_PROVEEDORES      MATERIALES.ID_PROVEEDORES%TYPE,
P_NOMBRE              MATERIALES.NOMBRE%TYPE,
P_FECHA_INGRESO       MATERIALES.FECHA_INGRESO%TYPE,
P_FECHA_EGRESO        MATERIALES.FECHA_EGRESO%TYPE,
P_TAMAÑO              MATERIALES.TAMAÑO%TYPE,
P_CANTIDAD            MATERIALES.CANTIDAD%TYPE,
P_USO                 MATERIALES.USO%TYPE,
P_PRECIO              MATERIALES.PRECIO%TYPE
)
AS
BEGIN
INSERT INTO MATERIALES
(ID_MATERIALES,
ID_PROVEEDORES,   
NOMBRE, 
FECHA_INGRESO,  
FECHA_EGRESO,   
TAMAÑO,
CANTIDAD,
USO,
PRECIO
)
VALUES
(P_ID_MATERIALES,
P_ID_PROVEEDORES,
P_NOMBRE,   
P_FECHA_INGRESO, 
P_FECHA_EGRESO,  
P_TAMAÑO,   
P_CANTIDAD,
P_USO,
P_PRECIO
);
END INSERTAR_MATERIALES;

/

CREATE OR REPLACE PROCEDURE "GARCIA"."INSERTAR_PROVEEDORES" 
(P_ID_PROVEEDORES       PROVEEDORES.ID_PROVEEDORES%TYPE,
P_NOMBRE_EMPRESA        PROVEEDORES.NOMBRE_EMPRESA%TYPE,
P_PRODUCTO_SOLICITADO   PROVEEDORES.PRODUCTO_SOLICITADO%TYPE,
P_CEDULA_EMPRESA        PROVEEDORES.CEDULA_EMPRESA%TYPE,
P_FECHA_PEDIDO          PROVEEDORES.FECHA_PEDIDO%TYPE
)
AS
BEGIN
INSERT INTO PROVEEDORES
(ID_PROVEEDORES,   
NOMBRE_EMPRESA, 
PRODUCTO_SOLICITADO,  
CEDULA_EMPRESA,
FECHA_PEDIDO
)
VALUES
(P_ID_PROVEEDORES,    
P_NOMBRE_EMPRESA,   
P_PRODUCTO_SOLICITADO, 
P_CEDULA_EMPRESA,
P_FECHA_PEDIDO
);
END INSERTAR_PROVEEDORES;

/

CREATE OR REPLACE PROCEDURE "GARCIA"."INSERTAR_RESERVA" (
    p_id_reservas        IN reservas.id_reservas%TYPE,
    p_id_empleado        IN reservas.id_empleado%TYPE,
    p_id_herramienta     IN reservas.id_herramienta%TYPE,
    p_fecha_ingreso      IN reservas.fecha_ingreso%TYPE,
    p_fecha_egreso       IN reservas.fecha_egreso%TYPE,
    p_estado_herramienta IN reservas.estado_herramienta%TYPE
) AS
BEGIN
    INSERT INTO reservas (
        id_reservas,
        id_empleado,
        id_herramienta,
        fecha_ingreso,
        fecha_egreso,
        estado_herramienta
    ) VALUES (
        p_id_reservas,
        p_id_empleado,
        p_id_herramienta,
        p_fecha_ingreso,
        p_fecha_egreso,
        p_estado_herramienta
    );
END insertar_reserva;

/

CREATE OR REPLACE PROCEDURE "GARCIA"."INSERTAR_USUARIOS" 
(P_ID_USUARIO          USUARIOS.ID_USUARIO%TYPE,
P_ID_MATERIALES        USUARIOS.ID_MATERIALES%TYPE,
P_CONTRASEÑA           USUARIOS.CONTRASEÑA%TYPE,
P_NOMBRE               USUARIOS.NOMBRE%TYPE,
P_TELEFONO             USUARIOS.TELEFONO%TYPE,
P_EMAIL                USUARIOS.EMAIL%TYPE
)
AS
BEGIN
INSERT INTO USUARIOS
(ID_USUARIO,   
ID_MATERIALES, 
CONTRASEÑA,  
NOMBRE,
TELEFONO,
EMAIL
)
VALUES
(P_ID_USUARIO,    
P_ID_MATERIALES,   
P_CONTRASEÑA, 
P_NOMBRE,
P_TELEFONO,
P_EMAIL
);
END INSERTAR_USUARIOS;

/

CREATE OR REPLACE PROCEDURE "GARCIA"."MODIFICAR_EMPLEADOS" 
(P_ID_EMPLEADO        EMPLEADOS.ID_EMPLEADO%TYPE,
P_NOMBRE              EMPLEADOS.NOMBRE%TYPE,
P_PRIMER_APELLIDO     EMPLEADOS.PRIMER_APELLIDO%TYPE,
P_SEGUNDO_APELLIDO    EMPLEADOS.SEGUNDO_APELLIDO%TYPE,
P_TELEFONO            EMPLEADOS.TELEFONO%TYPE,
P_EMAIL                EMPLEADOS.EMAIL%TYPE,
P_PUESTO              EMPLEADOS.PUESTO%TYPE
)
AS
BEGIN
UPDATE EMPLEADOS SET
NOMBRE = P_NOMBRE,
PRIMER_APELLIDO = P_PRIMER_APELLIDO,
SEGUNDO_APELLIDO = P_SEGUNDO_APELLIDO,
TELEFONO = P_TELEFONO,
EMAIL = P_EMAIL,
PUESTO = P_PUESTO
WHERE ID_EMPLEADO = P_ID_EMPLEADO;
END MODIFICAR_EMPLEADOS;

/

  CREATE OR REPLACE PROCEDURE "GARCIA"."MODIFICAR_FACTURA" 
(P_ID_FACTURAS       FACTURACION.ID_FACTURAS%TYPE,
P_ID_MATERIALES         FACTURACION.ID_MATERIALES%TYPE,
P_FECHA_FACTURA      FACTURACION.FECHA_FACTURA%TYPE,
P_MONTO              FACTURACION.MONTO%TYPE
)
AS
BEGIN
UPDATE FACTURACION SET
ID_MATERIALES = P_ID_MATERIALES,
FECHA_FACTURA = P_FECHA_FACTURA,
MONTO = P_MONTO
WHERE ID_FACTURAS = P_ID_FACTURAS;
END MODIFICAR_FACTURA;

/

CREATE OR REPLACE PROCEDURE "GARCIA"."MODIFICAR_HERRAMIENTA" 
(P_ID_HERRAMIENTA     HERRAMIENTAS.ID_HERRAMIENTA%TYPE,
P_ID_PROVEEDORES      HERRAMIENTAS.ID_PROVEEDORES%TYPE,
P_NOMBRE              HERRAMIENTAS.NOMBRE%TYPE,
P_TIPO_HERRAMIENTA    HERRAMIENTAS.TIPO_HERRAMIENTA%TYPE,
P_USO_HERRAMIENTA     HERRAMIENTAS.USO_HERRAMIENTA%TYPE
)
AS
BEGIN
UPDATE HERRAMIENTAS SET
ID_PROVEEDORES = P_ID_PROVEEDORES,
NOMBRE = P_NOMBRE,
TIPO_HERRAMIENTA = P_TIPO_HERRAMIENTA,
USO_HERRAMIENTA = P_USO_HERRAMIENTA
WHERE ID_HERRAMIENTA = P_ID_HERRAMIENTA;
END MODIFICAR_HERRAMIENTA;

/

CREATE OR REPLACE PROCEDURE "GARCIA"."MODIFICAR_HISTORIAL_PRESTAMOS" 
(P_ID_HISTORIAL       HISTORIAL_PRESTAMOS.ID_HISTORIAL%TYPE,
P_ID_HERRAMIENTA      HISTORIAL_PRESTAMOS.ID_HERRAMIENTA%TYPE,
P_ID_EMPLEADO         HISTORIAL_PRESTAMOS.ID_EMPLEADO%TYPE,
P_ID_RESERVAS         HISTORIAL_PRESTAMOS.ID_RESERVAS%TYPE,
P_ID_MANTENIMIENTO    HISTORIAL_PRESTAMOS.ID_MANTENIMIENTO%TYPE
)
AS
BEGIN
UPDATE HISTORIAL_PRESTAMOS SET
ID_HERRAMIENTA = P_ID_HERRAMIENTA,
ID_EMPLEADO = P_ID_EMPLEADO,
ID_RESERVAS = P_ID_RESERVAS,
ID_MANTENIMIENTO = P_ID_MANTENIMIENTO
WHERE ID_HISTORIAL = P_ID_HISTORIAL;
END MODIFICAR_HISTORIAL_PRESTAMOS;

/

CREATE OR REPLACE PROCEDURE "GARCIA"."MODIFICAR_MANTENIMIENTO" 
(P_ID_MANTENIMIENTO   MANTENIMIENTO.ID_MANTENIMIENTO%TYPE,
P_ID_HERRAMIENTA      MANTENIMIENTO.ID_HERRAMIENTA%TYPE,
P_FECHA_INGRESO       MANTENIMIENTO.FECHA_INGRESO%TYPE,
P_FECHA_EGRESO        MANTENIMIENTO.FECHA_EGRESO%TYPE
)
AS
BEGIN
UPDATE MANTENIMIENTO SET
ID_HERRAMIENTA = P_ID_HERRAMIENTA,
FECHA_INGRESO = P_FECHA_INGRESO,
FECHA_EGRESO = P_FECHA_EGRESO
WHERE ID_MANTENIMIENTO = P_ID_MANTENIMIENTO;
END MODIFICAR_MANTENIMIENTO;

/

CREATE OR REPLACE PROCEDURE "GARCIA"."MODIFICAR_MATERIALES" 
(P_ID_MATERIALES      MATERIALES.ID_MATERIALES%TYPE,
P_ID_PROVEEDORES      MATERIALES.ID_PROVEEDORES%TYPE,
P_NOMBRE              MATERIALES.NOMBRE%TYPE,
P_FECHA_INGRESO       MATERIALES.FECHA_INGRESO%TYPE,
P_FECHA_EGRESO        MATERIALES.FECHA_EGRESO%TYPE,
P_TAMAÑO              MATERIALES.TAMAÑO%TYPE,
P_CANTIDAD            MATERIALES.CANTIDAD%TYPE,
P_USO                 MATERIALES.USO%TYPE,
P_PRECIO              MATERIALES.PRECIO%TYPE
)
AS
BEGIN
UPDATE  MATERIALES SET
ID_PROVEEDORES = P_ID_PROVEEDORES,
NOMBRE = P_NOMBRE,
FECHA_INGRESO = P_FECHA_INGRESO,
FECHA_EGRESO = P_FECHA_EGRESO,
TAMAÑO = P_TAMAÑO,
CANTIDAD = P_CANTIDAD,
USO = P_USO,
PRECIO = P_PRECIO
WHERE ID_MATERIALES = P_ID_MATERIALES;
END MODIFICAR_MATERIALES;

/

CREATE OR REPLACE PROCEDURE "GARCIA"."MODIFICAR_PROVEEDORES" 
(P_ID_PROVEEDORES       PROVEEDORES.ID_PROVEEDORES%TYPE,
P_NOMBRE_EMPRESA        PROVEEDORES.NOMBRE_EMPRESA%TYPE,
P_PRODUCTO_SOLICITADO   PROVEEDORES.PRODUCTO_SOLICITADO%TYPE,
P_CEDULA_EMPRESA        PROVEEDORES.CEDULA_EMPRESA%TYPE,
P_FECHA_PEDIDO          PROVEEDORES.FECHA_PEDIDO%TYPE
)
AS
BEGIN
UPDATE PROVEEDORES SET
NOMBRE_EMPRESA = P_NOMBRE_EMPRESA,
PRODUCTO_SOLICITADO = P_PRODUCTO_SOLICITADO,
CEDULA_EMPRESA = P_CEDULA_EMPRESA,
FECHA_PEDIDO = P_FECHA_PEDIDO
WHERE ID_PROVEEDORES = P_ID_PROVEEDORES;
END MODIFICAR_PROVEEDORES;

/

CREATE OR REPLACE PROCEDURE "GARCIA"."MODIFICAR_RESERVA" 
(P_ID_RESERVAS         RESERVAS.ID_RESERVAS%TYPE,
P_ID_EMPLEADO          RESERVAS.ID_EMPLEADO%TYPE,
P_ID_HERRAMIENTA       RESERVAS.ID_HERRAMIENTA%TYPE,
P_FECHA_INGRESO        RESERVAS.FECHA_INGRESO%TYPE,
P_FECHA_EGRESO         RESERVAS.FECHA_EGRESO%TYPE,
P_ESTADO_HERRAMIENTA   RESERVAS.ESTADO_HERRAMIENTA%TYPE
)
AS
BEGIN
UPDATE  RESERVAS SET
ID_EMPLEADO = P_ID_EMPLEADO,
ID_HERRAMIENTA = P_ID_HERRAMIENTA,
FECHA_INGRESO = P_FECHA_INGRESO,
FECHA_EGRESO = P_FECHA_EGRESO,
ESTADO_HERRAMIENTA = P_ESTADO_HERRAMIENTA
WHERE ID_RESERVAS = P_ID_RESERVAS;
END MODIFICAR_RESERVA;

/

CREATE OR REPLACE PROCEDURE "GARCIA"."MODIFICAR_USUARIOS" 
(P_ID_USUARIO          USUARIOS.ID_USUARIO%TYPE,
P_ID_MATERIALES        USUARIOS.ID_MATERIALES%TYPE,
P_CONTRASEÑA           USUARIOS.CONTRASEÑA%TYPE,
P_NOMBRE               USUARIOS.NOMBRE%TYPE,
P_TELEFONO             USUARIOS.TELEFONO%TYPE,
P_EMAIL                USUARIOS.EMAIL%TYPE
)
AS
BEGIN
UPDATE USUARIOS SET
ID_MATERIALES = P_ID_MATERIALES,
CONTRASEÑA = P_CONTRASEÑA,
NOMBRE = P_NOMBRE,
TELEFONO = P_TELEFONO,
EMAIL = P_EMAIL
WHERE ID_USUARIO = P_ID_USUARIO;
END MODIFICAR_USUARIOS;

/

----- vistas ------

CREATE OR REPLACE VIEW MOSTRAR_USUARIOS
AS
SELECT A.NOMBRE, A.TELEFONO, A.EMAIL, B.NOMBRE AS MATERIAL
FROM USUARIOS A
INNER JOIN MATERIALES B ON A.ID_MATERIALES = B.ID_MATERIALES;

CREATE OR REPLACE VIEW MOSTRAR_RESERVAS
AS
SELECT A.ID_RESERVAS, B.NOMBRE AS EMPLEADO, C.NOMBRE AS HERRAMIENTA, A.FECHA_INGRESO, A.FECHA_EGRESO, A.ESTADO_HERRAMIENTA
FROM RESERVAS A
INNER JOIN EMPLEADOS B ON A.ID_EMPLEADO = B.ID_EMPLEADO
INNER JOIN HERRAMIENTAS C ON A.ID_HERRAMIENTA = C.ID_HERRAMIENTA;

CREATE OR REPLACE VIEW MOSTRAR_PROVEEDORES
AS
SELECT *
FROM PROVEEDORES;

CREATE OR REPLACE VIEW MOSTRAR_EMPLEADO
AS
SELECT *
FROM EMPLEADOS;

CREATE OR REPLACE VIEW MOSTRAR_FACTURACION
AS
SELECT A.ID_FACTURAS, B.NOMBRE AS MATERIAL, A.FECHA_FACTURA, A.MONTO
FROM FACTURACION A
INNER JOIN MATERIALES B ON A.ID_MATERIALES = B.ID_MATERIALES;

CREATE OR REPLACE VIEW MOSTRAR_HERRAMIENTAS
AS
SELECT A.ID_HERRAMIENTA, A.NOMBRE, A.TIPO_HERRAMIENTA, A.USO_HERRAMIENTA,B.NOMBRE_EMPRESA AS PROVEEDOR
FROM HERRAMIENTAS A
INNER JOIN PROVEEDORES B ON A.ID_PROVEEDORES = B.ID_PROVEEDORES;

CREATE OR REPLACE VIEW MOSTRAR_MANTENIMIENTO
AS
SELECT A.ID_MANTENIMIENTO, B.NOMBRE AS HERRAMIENTA, A.FECHA_INGRESO, A.FECHA_EGRESO
FROM MANTENIMIENTO A
INNER JOIN HERRAMIENTAS B ON A.ID_HERRAMIENTA = B.ID_HERRAMIENTA;

CREATE OR REPLACE VIEW MOSTRAR_MATERIALES
AS
SELECT A.ID_MATERIALES, A.NOMBRE ,B.NOMBRE_EMPRESA AS PROVEEDOR, A.FECHA_INGRESO, A.FECHA_EGRESO, A.TAMAÑO, A.CANTIDAD, A.USO, A.PRECIO
FROM MATERIALES A
INNER JOIN PROVEEDORES B ON A.ID_PROVEEDORES = B.ID_PROVEEDORES;

CREATE OR REPLACE VIEW MOSTRAR_HISTORIAL_PRESTAMOS
AS
SELECT A.ID_MANTENIMIENTO, B.NOMBRE AS EMPLEADO, C.NOMBRE AS HERRAMIENTA, D.ID_RESERVAS AS RESERVA, E.ID_MANTENIMIENTO AS MANTENIMIENTO
FROM HISTORIAL_PRESTAMOS A
INNER JOIN EMPLEADOS B ON A.ID_EMPLEADO = B.ID_EMPLEADO
INNER JOIN HERRAMIENTAS C ON A.ID_HERRAMIENTA = C.ID_HERRAMIENTA
INNER JOIN RESERVAS D ON A.ID_RESERVAS = D.ID_RESERVAS
INNER JOIN MANTENIMIENTO E ON A.ID_MANTENIMIENTO = E.ID_MANTENIMIENTO;


CREATE TABLE REGISTRO(
ID_REGISTRO INT NOT NULL PRIMARY KEY,
ACCION VARCHAR(50),
FECHA_ACCION DATE,
ID_CONTENIDO INT
);

CREATE SEQUENCE SE_REGISTRO START WITH 1 INCREMENT BY 1;

----------------------  TRIGGER PARA INSERTS ----------------------------

CREATE OR REPLACE TRIGGER INSERTAR_EMPLEADO
AFTER INSERT ON EMPLEADOS
FOR EACH ROW
BEGIN
INSERT INTO REGISTRO(ID_REGISTRO,ACCION,FECHA_ACCION,ID_CONTENIDO)
VALUES(SE_REGISTRO.NEXTVAL,'Se Insertó Empleado',SYSDATE,:NEW.ID_EMPLEADO);
END;

CREATE OR REPLACE TRIGGER INSERTAR_FACTURACION
AFTER INSERT ON FACTURACION
FOR EACH ROW
BEGIN
INSERT INTO REGISTRO(ID_REGISTRO,ACCION,FECHA_ACCION,ID_CONTENIDO)
VALUES(SE_REGISTRO.NEXTVAL,'Se Insertó Factura',SYSDATE,:NEW.ID_FACTURAS);
END;

CREATE OR REPLACE TRIGGER INSERTAR_HERRAMIENTAS
AFTER INSERT ON HERRAMIENTAS
FOR EACH ROW
BEGIN
INSERT INTO REGISTRO(ID_REGISTRO,ACCION,FECHA_ACCION,ID_CONTENIDO)
VALUES(SE_REGISTRO.NEXTVAL,'Se Insertó Herramienta',SYSDATE,:NEW.ID_HERRAMIENTA);
END;

CREATE OR REPLACE TRIGGER INSERTAR_HISTORIAL_PRESTAMOS
AFTER INSERT ON HISTORIAL_PRESTAMOS
FOR EACH ROW
BEGIN
INSERT INTO REGISTRO(ID_REGISTRO,ACCION,FECHA_ACCION,ID_CONTENIDO)
VALUES(SE_REGISTRO.NEXTVAL,'Se Insertó Historial Prestamo',SYSDATE,:NEW.ID_HISTORIAL);
END;

CREATE OR REPLACE TRIGGER INSERTAR_MANTENIMIENTO
AFTER INSERT ON MANTENIMIENTO
FOR EACH ROW
BEGIN
INSERT INTO REGISTRO(ID_REGISTRO,ACCION,FECHA_ACCION,ID_CONTENIDO)
VALUES(SE_REGISTRO.NEXTVAL,'Se Insertó Mantenimiento',SYSDATE,:NEW.ID_MANTENIMIENTO);
END;

CREATE OR REPLACE TRIGGER INSERTAR_MATERIALES
AFTER INSERT ON MATERIALES
FOR EACH ROW
BEGIN
INSERT INTO REGISTRO(ID_REGISTRO,ACCION,FECHA_ACCION,ID_CONTENIDO)
VALUES(SE_REGISTRO.NEXTVAL,'Se Insertó Materiales',SYSDATE,:NEW.ID_MATERIALES);
END;

CREATE OR REPLACE TRIGGER INSERTAR_NOTIFICACIONES
AFTER INSERT ON NOTIFICACIONES
FOR EACH ROW
BEGIN
INSERT INTO REGISTRO(ID_REGISTRO,ACCION,FECHA_ACCION,ID_CONTENIDO)
VALUES(SE_REGISTRO.NEXTVAL,'Se Insertó Notificaciones',SYSDATE,:NEW.ID_NOTIFICACIONES);
END;

CREATE OR REPLACE TRIGGER INSERTAR_PROVEEDORES
AFTER INSERT ON PROVEEDORES
FOR EACH ROW
BEGIN
INSERT INTO REGISTRO(ID_REGISTRO,ACCION,FECHA_ACCION,ID_CONTENIDO)
VALUES(SE_REGISTRO.NEXTVAL,'Se Insertó Proveedor',SYSDATE,:NEW.ID_PROVEEDORES);
END;

CREATE OR REPLACE TRIGGER INSERTAR_RESERVAS
AFTER INSERT ON RESERVAS
FOR EACH ROW
BEGIN
INSERT INTO REGISTRO(ID_REGISTRO,ACCION,FECHA_ACCION,ID_CONTENIDO)
VALUES(SE_REGISTRO.NEXTVAL,'Se Insertó Reserva',SYSDATE,:NEW.ID_RESERVAS);
END;

CREATE OR REPLACE TRIGGER INSERTAR_USUARIOS
AFTER INSERT ON USUARIOS
FOR EACH ROW
BEGIN
INSERT INTO REGISTRO(ID_REGISTRO,ACCION,FECHA_ACCION,ID_CONTENIDO)
VALUES(SE_REGISTRO.NEXTVAL,'Se Insertó Usuario',SYSDATE,:NEW.ID_USUARIO);
END;

----------------------  TRIGGER PARA UPDATES ----------------------------

CREATE OR REPLACE TRIGGER UPDATE_EMPLEADO
AFTER UPDATE ON EMPLEADOS
FOR EACH ROW
BEGIN
INSERT INTO REGISTRO(ID_REGISTRO,ACCION,FECHA_ACCION,ID_CONTENIDO)
VALUES(SE_REGISTRO.NEXTVAL,'Se Actualizó Empleado',SYSDATE,:OLD.ID_EMPLEADO);
END;

CREATE OR REPLACE TRIGGER UPDATE_FACTURACION
AFTER UPDATE ON FACTURACION
FOR EACH ROW
BEGIN
INSERT INTO REGISTRO(ID_REGISTRO,ACCION,FECHA_ACCION,ID_CONTENIDO)
VALUES(SE_REGISTRO.NEXTVAL,'Se Actualizó Factura',SYSDATE,:OLD.ID_FACTURAS);
END;

CREATE OR REPLACE TRIGGER UPDATE_HERRAMIENTAS
AFTER UPDATE ON HERRAMIENTAS
FOR EACH ROW
BEGIN
INSERT INTO REGISTRO(ID_REGISTRO,ACCION,FECHA_ACCION,ID_CONTENIDO)
VALUES(SE_REGISTRO.NEXTVAL,'Se Actualizó Herramienta',SYSDATE,:OLD.ID_HERRAMIENTA);
END;

CREATE OR REPLACE TRIGGER UPDATE_HISTORIAL_PRESTAMOS
AFTER UPDATE ON HISTORIAL_PRESTAMOS
FOR EACH ROW
BEGIN
INSERT INTO REGISTRO(ID_REGISTRO,ACCION,FECHA_ACCION,ID_CONTENIDO)
VALUES(SE_REGISTRO.NEXTVAL,'Se Actualizó Historial Prestamo',SYSDATE,:OLD.ID_HISTORIAL);
END;

CREATE OR REPLACE TRIGGER UPDATE_MANTENIMIENTO
AFTER UPDATE ON MANTENIMIENTO
FOR EACH ROW
BEGIN
INSERT INTO REGISTRO(ID_REGISTRO,ACCION,FECHA_ACCION,ID_CONTENIDO)
VALUES(SE_REGISTRO.NEXTVAL,'Se Actualizó Mantenimiento',SYSDATE,:OLD.ID_MANTENIMIENTO);
END;

CREATE OR REPLACE TRIGGER UPDATE_MATERIALES
AFTER UPDATE ON MATERIALES
FOR EACH ROW
BEGIN
INSERT INTO REGISTRO(ID_REGISTRO,ACCION,FECHA_ACCION,ID_CONTENIDO)
VALUES(SE_REGISTRO.NEXTVAL,'Se Actualizó Materiales',SYSDATE,:OLD.ID_MATERIALES);
END;

CREATE OR REPLACE TRIGGER UPDATE_NOTIFICACIONES
AFTER UPDATE ON NOTIFICACIONES
FOR EACH ROW
BEGIN
INSERT INTO REGISTRO(ID_REGISTRO,ACCION,FECHA_ACCION,ID_CONTENIDO)
VALUES(SE_REGISTRO.NEXTVAL,'Se Actualizó Notificaciones',SYSDATE,:OLD.ID_NOTIFICACIONES);
END;

CREATE OR REPLACE TRIGGER UPDATE_PROVEEDORES
AFTER UPDATE ON PROVEEDORES
FOR EACH ROW
BEGIN
INSERT INTO REGISTRO(ID_REGISTRO,ACCION,FECHA_ACCION,ID_CONTENIDO)
VALUES(SE_REGISTRO.NEXTVAL,'Se Actualizó Proveedor',SYSDATE,:OLD.ID_PROVEEDORES);
END;

CREATE OR REPLACE TRIGGER UPDATE_RESERVAS
AFTER UPDATE ON RESERVAS
FOR EACH ROW
BEGIN
INSERT INTO REGISTRO(ID_REGISTRO,ACCION,FECHA_ACCION,ID_CONTENIDO)
VALUES(SE_REGISTRO.NEXTVAL,'Se Actualizó Reserva',SYSDATE,:OLD.ID_RESERVAS);
END;

CREATE OR REPLACE TRIGGER UPDATE_USUARIOS
AFTER UPDATE ON USUARIOS
FOR EACH ROW
BEGIN
INSERT INTO REGISTRO(ID_REGISTRO,ACCION,FECHA_ACCION,ID_CONTENIDO)
VALUES(SE_REGISTRO.NEXTVAL,'Se Actualizó Usuario',SYSDATE,:OLD.ID_USUARIO);
END;
----------------------  TRIGGER PARA DELETES ----------------------------

CREATE OR REPLACE TRIGGER DELETE_EMPLEADO
AFTER DELETE ON EMPLEADOS
FOR EACH ROW
BEGIN
INSERT INTO REGISTRO(ID_REGISTRO,ACCION,FECHA_ACCION,ID_CONTENIDO)
VALUES(SE_REGISTRO.NEXTVAL,'Se Eliminó Empleado',SYSDATE,:OLD.ID_EMPLEADO);
END;


CREATE OR REPLACE TRIGGER DELETE_FACTURACION
AFTER DELETE ON FACTURACION
FOR EACH ROW
BEGIN
INSERT INTO REGISTRO(ID_REGISTRO,ACCION,FECHA_ACCION,ID_CONTENIDO)
VALUES(SE_REGISTRO.NEXTVAL,'Se Eliminó Factura',SYSDATE,:OLD.ID_FACTURAS);
END;

CREATE OR REPLACE TRIGGER DELETE_HERRAMIENTAS
AFTER DELETE ON HERRAMIENTAS
FOR EACH ROW
BEGIN
INSERT INTO REGISTRO(ID_REGISTRO,ACCION,FECHA_ACCION,ID_CONTENIDO)
VALUES(SE_REGISTRO.NEXTVAL,'Se Eliminó Herramienta',SYSDATE,:OLD.ID_HERRAMIENTA);
END;

CREATE OR REPLACE TRIGGER DELETE_HISTORIAL_PRESTAMOS
AFTER DELETE ON HISTORIAL_PRESTAMOS
FOR EACH ROW
BEGIN
INSERT INTO REGISTRO(ID_REGISTRO,ACCION,FECHA_ACCION,ID_CONTENIDO)
VALUES(SE_REGISTRO.NEXTVAL,'Se Eliminó Historial Prestamo',SYSDATE,:OLD.ID_HISTORIAL);
END;

CREATE OR REPLACE TRIGGER DELETE_MANTENIMIENTO
AFTER DELETE ON MANTENIMIENTO
FOR EACH ROW
BEGIN
INSERT INTO REGISTRO(ID_REGISTRO,ACCION,FECHA_ACCION,ID_CONTENIDO)
VALUES(SE_REGISTRO.NEXTVAL,'Se Eliminó Mantenimiento',SYSDATE,:OLD.ID_MANTENIMIENTO);
END;

CREATE OR REPLACE TRIGGER DELETE_MATERIALES
AFTER DELETE ON MATERIALES
FOR EACH ROW
BEGIN
INSERT INTO REGISTRO(ID_REGISTRO,ACCION,FECHA_ACCION,ID_CONTENIDO)
VALUES(SE_REGISTRO.NEXTVAL,'Se Eliminó Materiales',SYSDATE,:OLD.ID_MATERIALES);
END;

CREATE OR REPLACE TRIGGER DELETE_NOTIFICACIONES
AFTER DELETE ON NOTIFICACIONES
FOR EACH ROW
BEGIN
INSERT INTO REGISTRO(ID_REGISTRO,ACCION,FECHA_ACCION,ID_CONTENIDO)
VALUES(SE_REGISTRO.NEXTVAL,'Se Eliminó Notificaciones',SYSDATE,:OLD.ID_NOTIFICACIONES);
END;

CREATE OR REPLACE TRIGGER DELETE_PROVEEDORES
AFTER DELETE ON PROVEEDORES
FOR EACH ROW
BEGIN
INSERT INTO REGISTRO(ID_REGISTRO,ACCION,FECHA_ACCION,ID_CONTENIDO)
VALUES(SE_REGISTRO.NEXTVAL,'Se Eliminó Proveedor',SYSDATE,:OLD.ID_PROVEEDORES);
END;

CREATE OR REPLACE TRIGGER DELETE_RESERVAS
AFTER DELETE ON RESERVAS
FOR EACH ROW
BEGIN
INSERT INTO REGISTRO(ID_REGISTRO,ACCION,FECHA_ACCION,ID_CONTENIDO)
VALUES(SE_REGISTRO.NEXTVAL,'Se Eliminó Reserva',SYSDATE,:OLD.ID_RESERVAS);
END;

CREATE OR REPLACE TRIGGER DELETE_USUARIOS
AFTER DELETE ON USUARIOS
FOR EACH ROW
BEGIN
INSERT INTO REGISTRO(ID_REGISTRO,ACCION,FECHA_ACCION,ID_CONTENIDO)
VALUES(SE_REGISTRO.NEXTVAL,'Se Eliminó Usuario',SYSDATE,:OLD.ID_USUARIO);
END;


SELECT * FROM REGISTRO;