------ PROCESOS INSERTAR ------

CREATE OR REPLACE PROCEDURE INSERTAR_HERRAMIENTA
(P_ID_HERRAMIENTA     HERRAMIENTAS.ID_HERRAMIENTA%TYPE,
P_ID_PROVEEDORES      HERRAMIENTAS.ID_PROVEEEDORES%TYPE,
P_NOMBRE              HERRAMIENTAS.NOMBRE%TYPE,
P_TIPO_HERRAMIENTA    HERRAMIENTAS.TIPO_HERRAMIENTA%TYPE,
P_USO_HERRAMIENTA     HERRAMIENTAS.USO_HERRAMIENTA%TYPE
)
AS
BEGIN
INSERT INTO HERRAMIENTAS
(ID_HERRAMIENTA,
ID_PROVEEDORES,
NOMBRE,
TIPO_HERRAMIENTA,
USO_HERRAMIENTA
)
VALUES
(P_ID_HERRAMIENTA,
P_ID_PROVEEDORES,
P_NOMBRE,
P_TIPO_HERRAMIENTA,
P_USO_HERRAMIENTA
);
END INSERTAR_HERRAMIENTA;

CREATE OR REPLACE PROCEDURE INSERTAR_RESERVA
(P_ID_RESERVAS         RESERVAS.ID_RESERVAS%TYPE,
P_ID_EMPLEADO          RESERVAS.ID_EMPLEADO%TYPE,
P_ID_HERRAMIENTA       RESERVAS.ID_HERRAMIENTA%TYPE,
P_FECHA_INGRESO        RESERVAS.FECHA_INGRESO%TYPE,
P_FECHA_EGRESO         RESERVAS.FECHA_EGRESO%TYPE,
P_ESTADO_HERRAMIENTA   RESERVAS.ESTADO_HERRAMIENTA%TYPE
)
AS
BEGIN
INSERT INTO RESERVAS
(ID_RESERVAS,    
ID_EMPLEADO,   
ID_HERRAMIENTA, 
FECHA_INGRESO,  
FECHA_EGRESO,   
ESTADO_HERRAMIENTA
)
VALUES
(P_ID_RESERVA,    
P_ID_EMPLEADO,   
P_ID_HERRAMIENTA, 
P_FECHA_INGRESO,  
P_FECHA_EGRESO,   
P_ESTADO_HERRAMIENTA 
);
END INSERTAR_RESERVA;

CREATE OR REPLACE PROCEDURE INSERTAR_EMPLEADOS
(P_ID_EMPLEADO        EMPLEADOS.ID_EMPLEADO%TYPE,
P_NOMBRE              EMPLEADOS.NOMBRE%TYPE,
P_PRIMER_APELLIDO     EMPLEADOS.PRIMER_APELLIDO%TYPE,
P_SEGUNDO_APELLIDO    EMPLEADOS.SEGUNDO_APELLIDO%TYPE,
P_TELEFONO            EMPLEADOS.TELEFONO%TYPE,
P_MAIL                EMPLEADOS.MAIL%TYPE,
P_PUESTO              EMPLEADOS.PUESTO%TYPE
)
AS
BEGIN
INSERT INTO EMPLEADOS
(ID_EMPLEADO,   
NOMBRE, 
PRIMER_APELLIDO,  
SEGUNDO_APELLIDO,   
TELEFONO,
MAIL,
PUESTO
)
VALUES
(P_ID_EMPLEADO,    
P_NOMBRE,   
P_PRIMER_APELLIDO, 
P_SEGUNDO_APELLIDO,  
P_TELEFONO,   
P_MAIL,
P_PUESTO
);
END INSERTAR_EMPLEADOS;

CREATE OR REPLACE PROCEDURE INSERTAR_FACTURA
(P_ID_FACTURAS       FACTURACION.ID_FACTURAS%TYPE,
P_MATERIALES         FACTURACION.MATERIALES%TYPE,
P_FECHA_FACTURA      FACTURACION.FECHA_FACTURA%TYPE,
P_MONTO              FACTURACION.MONTO%TYPE
)
AS
BEGIN
INSERT INTO FACTURACION
(ID_FACTURAS,   
MATERIALES, 
FECHA_FACTURA,  
MONTO
)
VALUES
(P_ID_FACTURAS,    
P_MATERIALES,   
P_FECHA_FACTURA, 
P_MONTO
);
END INSERTAR_FACTURA;

CREATE OR REPLACE PROCEDURE INSERTAR_MANTENIMIENTO
(P_ID_MANTENIMIENTO   MANTENIMIENTO.ID_MANTENIMIENTO%TYPE,
P_ID_HERRAMIENTA      MANTENIMIENTO.ID_HERRAMIENTA%TYPE,
P_FECHA_INGRESO       MANTENIMIENTO.FECHA_INGRESO%TYPE,
P_FECHA_EGRESO        MANTENIMIENTO.FECHA_EGRESO%TYPE
)
AS
BEGIN
INSERT INTO MANTENIMIENTO
(ID_MANTENIMIENTO,   
ID_HERRAMIENTA, 
FECHA_INGRESO,  
FECHA_EGRESO
)
VALUES
(P_ID_MANTENIMIENTO,    
P_ID_HERRAMIENTA,   
P_FECHA_INGRESO, 
P_FECHA_EGRESO
);
END INSERTAR_MANTENIMIENTO;



CREATE OR REPLACE PROCEDURE INSERTAR_HISTORIAL_PRESTAMOS
(P_ID_HISTORIAL       HISTORIAL_PRESTAMOS.ID_HISTORIAL%TYPE,
P_ID_HERRAMIENTA      HISTORIAL_PRESTAMOS.ID_HERRAMIENTA%TYPE,
P_ID_EMPLEADO         HISTORIAL_PRESTAMOS.ID_EMPLEADO%TYPE,
P_ID_RESERVAS         HISTORIAL_PRESTAMOS.ID_RESERVAS%TYPE,
P_ID_MANTENIMIENTO    HISTORIAL_PRESTAMOS.ID_MANTENIMIENTO%TYPE
)
AS
BEGIN
INSERT INTO HISTORIAL_PRESTAMOS
(ID_HISTORIAL,   
ID_HERRAMIENTA, 
ID_EMPLEADO,  
ID_RESERVAS,
ID_MANTENIMIENTO
)
VALUES
(P_ID_HISTORIAL,    
P_ID_HERRAMIENTA,   
P_ID_EMPLEADO, 
P_ID_RESERVAS,
P_ID_MANTENIMIENTO
);
END INSERTAR_HISTORIAL_PRESTAMOS;


CREATE OR REPLACE PROCEDURE INSERTAR_MATERIALES
(P_ID_MATERIALES      MATERIALES.ID_EMPLEADO%TYPE,
P_ID_PROVEEDORES      MATERIALES.ID_PROVEEDORES%TYPE,
P_NOMBRE              MATERIALES.NOMBRE%TYPE,
P_FECHA_INGRESO       MATERIALES.FECHA_INGRESO%TYPE,
P_FECHA_EGRESO        MATERIALES.FECHA_EGRESO%TYPE,
P_TAMAÑO              MATERIALES.TAMAÑO%TYPE,
P_CANTIDAD            MATERIALES.CANTIDAD%TYPE,
P_USO                 MATERIALES.USO%TYPE,
P_PRECIO              MATERIALES.PRECIO%TYPE
)
AS
BEGIN
INSERT INTO MATERIALES
(ID_MATERIALES,
ID_PROVEEDORES,   
NOMBRE, 
FECHA_INGRESO,  
FECHA_EGRESO,   
TAMAÑO,
CANTIDAD,
USO,
PRECIO
)
VALUES
(P_ID_MATERIALES,
P_ID_PROVEEDORES,
P_NOMBRE,   
P_FECHA_INGRESO, 
P_FECHA_EGRESO,  
P_TAMAÑO,   
P_CANTIDAD,
P_USO,
P_PRECIO
);
END INSERTAR_MATERIALES;


CREATE OR REPLACE PROCEDURE INSERTAR_PROVEEDORES
(P_ID_PROVEEDORES       PROVEEDORES.ID_PROVEEDORES%TYPE,
P_NOMBRE_EMPRESA        PROVEEDORES.NOMBRE_EMPRESA%TYPE,
P_PRODUCTO_SOLICITADO   PROVEEDORES.PRODUCTO_SOLICITADO%TYPE,
P_CEDULA_EMPRESA        PROVEEDORES.CEDULA_EMPRESA%TYPE,
P_FECHA_PEDIDO          PROVEEDORES.FECHA_PEDIDO%TYPE
)
AS
BEGIN
INSERT INTO PROVEEDORES
(ID_PROVEEDORES,   
NOMBRE_EMPRESA, 
PRODUCTO_SOLICITADO,  
CEDULA_EMPRESA,
FECHA_PEDIDO
)
VALUES
(P_ID_PROVEEDORES,    
P_NOMBRE_EMPRESA,   
P_PRODUCTO_SOLICITADO, 
P_CEDULA_EMPRESA,
P_FECHA_PEDIDO
);
END INSERTAR_PROVEEDORES;

CREATE OR REPLACE PROCEDURE INSERTAR_USUARIOS
(P_ID_USUARIO          USUARIOS.ID_USUARIO%TYPE,
P_ID_MATERIALES        USUARIOS.ID_MATERIALES%TYPE,
P_CONTRASEÑA           USUARIOS.CONTRASEÑA%TYPE,
P_NOMBRE               USUARIOS.NOMBRE%TYPE,
P_TELEFONO             USUARIOS.TELEFONO%TYPE,
P_EMAIL                USUARIOS.EMAIL%TYPE
)
AS
BEGIN
INSERT INTO USUARIOS
(ID_USUARIO,   
ID_MATERIALES, 
CONTRASEÑA,  
NOMBRE,
TELEFONO,
EMAIL
)
VALUES
(P_ID_USUARIO,    
P_ID_MATERIALES,   
P_CONTRASEÑA, 
P_NOMBRE,
P_TELEFONO,
P_EMAIL
);
END INSERTAR_USUARIOS;


------ PROCESOS ELIMINAR ------

CREATE OR REPLACE PROCEDURE ELIMINAR_HERRAMIENTA
(P_ID_HERRAMIENTA     HERRAMIENTAS.ID_HERRAMIENTA%TYPE,
P_ID_PROVEEDORES      HERRAMIENTAS.ID_PROVEEEDORES%TYPE,
P_NOMBRE              HERRAMIENTAS.NOMBRE%TYPE,
P_TIPO_HERRAMIENTA    HERRAMIENTAS.TIPO_HERRAMIENTA%TYPE,
P_USO_HERRAMIENTA     HERRAMIENTAS.USO_HERRAMIENTA%TYPE
)
AS
BEGIN
DELETE FROM HERRAMIENTAS
WHERE ID_HERRAMIENTA = P_ID_HERRAMIENTA;
END ELIMINAR_HERRAMIENTA;

CREATE OR REPLACE PROCEDURE ELIMINAR_RESERVA
(P_ID_RESERVAS         RESERVAS.ID_RESERVAS%TYPE,
P_ID_EMPLEADO          RESERVAS.ID_EMPLEADO%TYPE,
P_ID_HERRAMIENTA       RESERVAS.ID_HERRAMIENTA%TYPE,
P_FECHA_INGRESO        RESERVAS.FECHA_INGRESO%TYPE,
P_FECHA_EGRESO         RESERVAS.FECHA_EGRESO%TYPE,
P_ESTADO_HERRAMIENTA   RESERVAS.ESTADO_HERRAMIENTA%TYPE
)
AS
BEGIN
DELETE FROM RESERVAS
WHERE ID_RESERVAS = P_ID_RESERVAS;
END ELIMINAR_RESERVA;

CREATE OR REPLACE PROCEDURE ELIMINAR_EMPLEADOS
(P_ID_EMPLEADO        EMPLEADOS.ID_EMPLEADO%TYPE,
P_NOMBRE              EMPLEADOS.NOMBRE%TYPE,
P_PRIMER_APELLIDO     EMPLEADOS.PRIMER_APELLIDO%TYPE,
P_SEGUNDO_APELLIDO    EMPLEADOS.SEGUNDO_APELLIDO%TYPE,
P_TELEFONO            EMPLEADOS.TELEFONO%TYPE,
P_MAIL                EMPLEADOS.MAIL%TYPE,
P_PUESTO              EMPLEADOS.PUESTO%TYPE
)
AS
BEGIN
DELETE FROM EMPLEADOS
WHERE ID_EMPLEADO = P_ID_EMPLEADO;
END ELIMINAR_EMPLEADOS;

CREATE OR REPLACE PROCEDURE ELIMINAR_FACTURA
(P_ID_FACTURAS       FACTURACION.ID_FACTURAS%TYPE,
P_MATERIALES         FACTURACION.MATERIALES%TYPE,
P_FECHA_FACTURA      FACTURACION.FECHA_FACTURA%TYPE,
P_MONTO              FACTURACION.MONTO%TYPE
)
AS
BEGIN
DELETE FROM FACTURACION
WHERE ID_FACTURAS = P_ID_FACTURAS;
END ELIMINAR_FACTURA;

CREATE OR REPLACE PROCEDURE ELIMINAR_MANTENIMIENTO
(P_ID_MANTENIMIENTO   MANTENIMIENTO.ID_MANTENIMIENTO%TYPE,
P_ID_HERRAMIENTA      MANTENIMIENTO.ID_HERRAMIENTA%TYPE,
P_FECHA_INGRESO       MANTENIMIENTO.FECHA_INGRESO%TYPE,
P_FECHA_EGRESO        MANTENIMIENTO.FECHA_EGRESO%TYPE
)
AS
BEGIN
DELETE FROM MANTENIMIENTO
WHERE ID_MANTENIMIENTO = P_ID_MANTENIMIENTO;
END ELIMINAR_MANTENIMIENTO;



CREATE OR REPLACE PROCEDURE ELIMINAR_HISTORIAL_PRESTAMOS
(P_ID_HISTORIAL       HISTORIAL_PRESTAMOS.ID_HISTORIAL%TYPE,
P_ID_HERRAMIENTA      HISTORIAL_PRESTAMOS.ID_HERRAMIENTA%TYPE,
P_ID_EMPLEADO         HISTORIAL_PRESTAMOS.ID_EMPLEADO%TYPE,
P_ID_RESERVAS         HISTORIAL_PRESTAMOS.ID_RESERVAS%TYPE,
P_ID_MANTENIMIENTO    HISTORIAL_PRESTAMOS.ID_MANTENIMIENTO%TYPE
)
AS
BEGIN
DELETE FROM HISTORIAL_PRESTAMOS
WHERE ID_HISTORIAL = P_ID_HISTORIAL;
END ELIMINAR_HISTORIAL_PRESTAMOS;


CREATE OR REPLACE PROCEDURE ELIMINAR_MATERIALES
(P_ID_MATERIALES      MATERIALES.ID_MATERIALES%TYPE,
P_ID_PROVEEDORES      MATERIALES.ID_PROVEEDORES%TYPE,
P_NOMBRE              MATERIALES.NOMBRE%TYPE,
P_FECHA_INGRESO       MATERIALES.FECHA_INGRESO%TYPE,
P_FECHA_EGRESO        MATERIALES.FECHA_EGRESO%TYPE,
P_TAMAÑO              MATERIALES.TAMAÑO%TYPE,
P_CANTIDAD            MATERIALES.CANTIDAD%TYPE,
P_USO                 MATERIALES.USO%TYPE,
P_PRECIO              MATERIALES.PRECIO%TYPE
)
AS
BEGIN
DELETE FROM MATERIALES
WHERE ID_MATERIALES = P_ID_MATERIALES;
END ELIMINAR_MATERIALES;


CREATE OR REPLACE PROCEDURE ELIMINAR_PROVEEDORES
(P_ID_PROVEEDORES       PROVEEDORES.ID_PROVEEDORES%TYPE,
P_NOMBRE_EMPRESA        PROVEEDORES.NOMBRE_EMPRESA%TYPE,
P_PRODUCTO_SOLICITADO   PROVEEDORES.PRODUCTO_SOLICITADO%TYPE,
P_CEDULA_EMPRESA        PROVEEDORES.CEDULA_EMPRESA%TYPE,
P_FECHA_PEDIDO          PROVEEDORES.FECHA_PEDIDO%TYPE
)
AS
BEGIN
DELETE FROM PROVEEDORES
WHERE ID_PROVEEDORES = P_ID_PROVEEDORES;
END ELIMINAR_PROVEEDORES;

CREATE OR REPLACE PROCEDURE ELIMINAR_USUARIOS
(P_ID_USUARIO          USUARIOS.ID_USUARIO%TYPE,
P_ID_MATERIALES        USUARIOS.ID_MATERIALES%TYPE,
P_CONTRASEÑA           USUARIOS.CONTRASEÑA%TYPE,
P_NOMBRE               USUARIOS.NOMBRE%TYPE,
P_TELEFONO             USUARIOS.TELEFONO%TYPE,
P_EMAIL                USUARIOS.EMAIL%TYPE
)
AS
BEGIN
DELETE FROM USUARIOS
WHERE ID_USUARIO = P_ID_USUARIO;
END ELIMINAR_USUARIOS;


------ PROCESOS MODIFICAR ------

CREATE OR REPLACE PROCEDURE MODIFICAR_HERRAMIENTA
(P_ID_HERRAMIENTA     HERRAMIENTAS.ID_HERRAMIENTA%TYPE,
P_ID_PROVEEDORES      HERRAMIENTAS.ID_PROVEEEDORES%TYPE,
P_NOMBRE              HERRAMIENTAS.NOMBRE%TYPE,
P_TIPO_HERRAMIENTA    HERRAMIENTAS.TIPO_HERRAMIENTA%TYPE,
P_USO_HERRAMIENTA     HERRAMIENTAS.USO_HERRAMIENTA%TYPE
)
AS
BEGIN
UPDATE HERRAMIENTAS SET
ID_PROVEEEDORES = P_ID_PROVEEDORES,
NOMBRE = P_NOMBRE,
TIPO_HERRAMIENTA = P_TIPO_HERRAMIENTA,
USO_HERRAMIENTA = P_USO_HERRAMIENTA
WHERE ID_HERRAMIENTA = P_ID_HERRAMIENTA;
END MODIFICAR_HERRAMIENTA;

CREATE OR REPLACE PROCEDURE MODIFICAR_RESERVA
(P_ID_RESERVAS         RESERVAS.ID_RESERVAS%TYPE,
P_ID_EMPLEADO          RESERVAS.ID_EMPLEADO%TYPE,
P_ID_HERRAMIENTA       RESERVAS.ID_HERRAMIENTA%TYPE,
P_FECHA_INGRESO        RESERVAS.FECHA_INGRESO%TYPE,
P_FECHA_EGRESO         RESERVAS.FECHA_EGRESO%TYPE,
P_ESTADO_HERRAMIENTA   RESERVAS.ESTADO_HERRAMIENTA%TYPE
)
AS
BEGIN
UPDATE  RESERVAS SET
ID_EMPLEADO = P_ID_EMPLEADO,
ID_HERRAMIENTA = P_ID_HERRAMIENTA,
FECHA_INGRESO = P_FECHA_INGRESO,
FECHA_EGRESO = P_FECHA_EGRESO,
ESTADO_HERRAMIENTA = P_ESTADO_HERRAMIENTA
WHERE ID_RESERVAS = P_ID_RESERVAS;
END MODIFICAR_RESERVA;

CREATE OR REPLACE PROCEDURE MODIFICAR_EMPLEADOS
(P_ID_EMPLEADO        EMPLEADOS.ID_EMPLEADO%TYPE,
P_NOMBRE              EMPLEADOS.NOMBRE%TYPE,
P_PRIMER_APELLIDO     EMPLEADOS.PRIMER_APELLIDO%TYPE,
P_SEGUNDO_APELLIDO    EMPLEADOS.SEGUNDO_APELLIDO%TYPE,
P_TELEFONO            EMPLEADOS.TELEFONO%TYPE,
P_MAIL                EMPLEADOS.MAIL%TYPE,
P_PUESTO              EMPLEADOS.PUESTO%TYPE
)
AS
BEGIN
UPDATE EMPLEADOS SET
NOMBRE = P_NOMBRE,
PRIMER_APELLIDO = P_PRIMER_APELLIDO,
SEGUNDO_APELLIDO = P_SEGUNDO_APELLIDO,
TELEFONO = P_TELEFONO,
MAIL = P_MAIL,
PUESTO = P_PUESTO
WHERE ID_EMPLEADO = P_ID_EMPLEADO;
END MODIFICAR_EMPLEADOS;

CREATE OR REPLACE PROCEDURE MODIFICAR_FACTURA
(P_ID_FACTURAS       FACTURACION.ID_FACTURAS%TYPE,
P_MATERIALES         FACTURACION.MATERIALES%TYPE,
P_FECHA_FACTURA      FACTURACION.FECHA_FACTURA%TYPE,
P_MONTO              FACTURACION.MONTO%TYPE
)
AS
BEGIN
UPDATE FACTURACION SET
MATERIALES = P_MATERIALES,
FECHA_FACTURA = P_FECHA_FACTURA,
MONTO = P_MONTO
WHERE ID_FACTURAS = P_ID_FACTURAS;
END MODIFICAR_FACTURA;

CREATE OR REPLACE PROCEDURE MODIFICAR_MANTENIMIENTO
(P_ID_MANTENIMIENTO   MANTENIMIENTO.ID_MANTENIMIENTO%TYPE,
P_ID_HERRAMIENTA      MANTENIMIENTO.ID_HERRAMIENTA%TYPE,
P_FECHA_INGRESO       MANTENIMIENTO.FECHA_INGRESO%TYPE,
P_FECHA_EGRESO        MANTENIMIENTO.FECHA_EGRESO%TYPE
)
AS
BEGIN
UPDATE MANTENIMIENTO SET
ID_HERRAMIENTA = P_ID_HERRAMIENTA,
FECHA_INGRESO = P_FECHA_INGRESO,
FECHA_EGRESO = P_FECHA_EGRESO
WHERE ID_MANTENIMIENTO = P_ID_MANTENIMIENTO;
END MODIFICAR_MANTENIMIENTO;



CREATE OR REPLACE PROCEDURE MODIFICAR_HISTORIAL_PRESTAMOS
(P_ID_HISTORIAL       HISTORIAL_PRESTAMOS.ID_HISTORIAL%TYPE,
P_ID_HERRAMIENTA      HISTORIAL_PRESTAMOS.ID_HERRAMIENTA%TYPE,
P_ID_EMPLEADO         HISTORIAL_PRESTAMOS.ID_EMPLEADO%TYPE,
P_ID_RESERVAS         HISTORIAL_PRESTAMOS.ID_RESERVAS%TYPE,
P_ID_MANTENIMIENTO    HISTORIAL_PRESTAMOS.ID_MANTENIMIENTO%TYPE
)
AS
BEGIN
UPDATE HISTORIAL_PRESTAMOS SET
ID_HERRAMIENTA = P_ID_HERRAMIENTA,
ID_EMPLEADO = P_ID_EMPLEADO,
ID_RESERVAS = P_ID_RESERVAS,
ID_MANTENIMIENTO = P_ID_MANTENIMIENTO
WHERE ID_HISTORIAL = P_ID_HISTORIAL;
END MODIFICAR_HISTORIAL_PRESTAMOS;


CREATE OR REPLACE PROCEDURE MODIFICAR_MATERIALES
(P_ID_MATERIALES      MATERIALES.ID_MATERIALES%TYPE,
P_ID_PROVEEDORES      MATERIALES.ID_PROVEEDORES%TYPE,
P_NOMBRE              MATERIALES.NOMBRE%TYPE,
P_FECHA_INGRESO       MATERIALES.FECHA_INGRESO%TYPE,
P_FECHA_EGRESO        MATERIALES.FECHA_EGRESO%TYPE,
P_TAMAÑO              MATERIALES.TAMAÑO%TYPE,
P_CANTIDAD            MATERIALES.CANTIDAD%TYPE,
P_USO                 MATERIALES.USO%TYPE,
P_PRECIO              MATERIALES.PRECIO%TYPE
)
AS
BEGIN
UPDATE  MATERIALES SET
ID_PROVEEDORES = P_ID_PROVEEDORES,
NOMBRE = P_NOMBRE,
FECHA_INGRESO = P_FECHA_INGRESO,
FECHA_EGRESO = P_FECHA_EGRESO,
TAMAÑO = P_TAMAÑO,
CANTIDAD = P_CANTIDAD,
USO = P_USO,
PRECIO = P_PRECIO
WHERE ID_MATERIALES = P_ID_MATERIALES;
END MODIFICAR_MATERIALES;


CREATE OR REPLACE PROCEDURE MODIFICAR_PROVEEDORES
(P_ID_PROVEEDORES       PROVEEDORES.ID_PROVEEDORES%TYPE,
P_NOMBRE_EMPRESA        PROVEEDORES.NOMBRE_EMPRESA%TYPE,
P_PRODUCTO_SOLICITADO   PROVEEDORES.PRODUCTO_SOLICITADO%TYPE,
P_CEDULA_EMPRESA        PROVEEDORES.CEDULA_EMPRESA%TYPE,
P_FECHA_PEDIDO          PROVEEDORES.FECHA_PEDIDO%TYPE
)
AS
BEGIN
UPDATE PROVEEDORES SET
NOMBRE_EMPRESA = P_NOMBRE_EMPRESA,
PRODUCTO_SOLICITADO = P_PRODUCTO_SOLICITADO,
CEDULA_EMPRESA = P_CEDULA_EMPRESA,
FECHA_PEDIDO = P_FECHA_PEDIDO
WHERE ID_PROVEEDORES = P_ID_PROVEEDORES;
END MODIFICAR_PROVEEDORES;

CREATE OR REPLACE PROCEDURE MODIFICAR_USUARIOS
(P_ID_USUARIO          USUARIOS.ID_USUARIO%TYPE,
P_ID_MATERIALES        USUARIOS.ID_MATERIALES%TYPE,
P_CONTRASEÑA           USUARIOS.CONTRASEÑA%TYPE,
P_NOMBRE               USUARIOS.NOMBRE%TYPE,
P_TELEFONO             USUARIOS.TELEFONO%TYPE,
P_EMAIL                USUARIOS.EMAIL%TYPE
)
AS
BEGIN
UPDATE USUARIOS SET
ID_MATERIALES = P_ID_MATERIALES,
CONTRASEÑA = P_CONTRASEÑA,
NOMBRE = P_NOMBRE,
TELEFONO = P_TELEFONO,
EMAIL = P_EMAIL
WHERE ID_USUARIO = P_ID_USUARIO;
END MODIFICAR_USUARIOS;


----- vistas ------

CREATE OR REPLACE VIEW MOSTRAR_USUARIOS
AS
SELECT A.NOMBRE, A.TELEFONO, A.EMAIL, B.NOMBRE AS MATERIAL
FROM USUARIOS A
INNER JOIN MATERIALES B ON A.ID_MATERIALES = B.ID_MATERIALES;

CREATE OR REPLACE VIEW MOSTRAR_RESERVAS
AS
SELECT A.ID_RESERVA, B.NOMBRE AS EMPLEADO, C.NOMBRE AS HERRAMIENTA, A.FECHA_INGRESO, A.FECHA_EGRESO, A.ESTADO_HERRAMIENTA
FROM RESERVAS A
INNER JOIN EMPLEADOS B ON A.ID_EMPLEADO = B.ID_EMPLEADO
INNER JOIN HERRAMIENTAS C ON A.ID_HERRAMIENTA = C.ID_HERRAMIENTA;

CREATE OR REPLACE VIEW MOSTRAR_PROVEEDORES
AS
SELECT *
FROM PROVEEDORES;

CREATE OR REPLACE VIEW MOSTRAR_EMPLEADO
AS
SELECT *
FROM EMPLEADOS;

CREATE OR REPLACE VIEW MOSTRAR_FACTURACION
AS
SELECT A.ID_FACTURA, B.NOMBRE AS MATERIAL, A.FECHA_FACTURA, A.MONTO
FROM FACTURACION A
INNER JOIN MATERIALES B ON A.ID_MATERIAL = B.ID_MATERIAL;

CREATE OR REPLACE VIEW MOSTRAR_HERRAMIENTAS
AS
SELECT A.ID_HERRAMIENTA, A.NOMBRE, A.TIPO_HERRAMIENTA, A.USO_HERRAMIENTA,B.NOMBRE_EMPRESA AS PROVEEDOR
FROM HERRAMIENTAS A
INNER JOIN PROVEEDORES B ON A.ID_PROVEEDORES = B.ID_PROVEEDORES;

CREATE OR REPLACE VIEW MOSTRAR_MANTENIMIENTO
AS
SELECT A.ID_MANTENIMIENTO, B.NOMBRE AS HERRAMIENTA, A.FECHA_INGRESO, A.FECHA_EGRESO
FROM MANTENIMIENTO A
INNER JOIN HERRAMIENTAS B ON A.ID_HERRAMIENTA = B.ID_HERRAMIENTA;

CREATE OR REPLACE VIEW MOSTRAR_MATERIALES
AS
SELECT A.ID_MATERIAL, A.NOMBRE ,B.NOMBRE_EMPRESA AS PROVEEDOR, A.FECHA_INGRESO, A.FECHA_EGRESO, A.TAMAÑO, A.CANTIDAD, A.USO, A.PRECIO
FROM MATERIALES A
INNER JOIN PROVEEDORES B ON A.ID_PROVEEDORES = B.ID_PROVEEDORES;

CREATE OR REPLACE VIEW MOSTRAR_HISTORIAL_PRESTAMOS
AS
SELECT A.ID_MANTENIMIENTO, B.NOMBRE AS EMPLEADO, C.NOMBRE AS HERRAMIENTA, C.ID_RESERVAS AS RESERVA, D.ID_MANTENIMIENTO AS MANTENIMIENTO
FROM HISTORIAL_PRESTAMOS A
INNER JOIN EMPLEADOS B ON A.ID_EMPLEADO = B.ID_EMPLEADO
INNER JOIN HERRAMIENTAS C ON A.ID_HERRAMIENTA = C.ID_HERRAMIENTA
INNER JOIN RESERVAS D ON A.ID_RESERVAS = D.ID_RESERVAS
INNER JOIN MANTENIMIENTO E ON A.ID_MANTENIMIENTO = E.ID_MANTENIMIENTO;

